/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Administrator;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;
import vo.uservo.UserInfoVO;

/**
 *
 * @author zili chen
 */
public class adminMainPanel extends javax.swing.JPanel {
    AdminMain frame ;
    JPanel p;
    /**
     * Creates new form adminMainPanel
     */
    public adminMainPanel(String name,AdminMain f) {
        initComponents();
        nameLogo2.setText(name);
       frame = f;
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelPanel2 = new javax.swing.JPanel();
        peopleLogo2 = new javax.swing.JLabel();
        nameLogo2 = new javax.swing.JLabel();
        arrowLogo2 = new javax.swing.JLabel();
        currentLogo2 = new javax.swing.JLabel();
        backLogo2 = new javax.swing.JLabel();
        backLabel2 = new javax.swing.JLabel();
        homeLogo2 = new javax.swing.JLabel();
        homeLabel2 = new javax.swing.JLabel();
        exitLogo2 = new javax.swing.JLabel();
        exitLabel2 = new javax.swing.JLabel();
        viewInfoButton = new javax.swing.JButton();
        viewInfoLabel = new javax.swing.JLabel();
        addUserLabel = new javax.swing.JLabel();
        addUserButton = new javax.swing.JButton();
        keyLabel = new javax.swing.JLabel();
        perInfoButton = new javax.swing.JButton();
        perInfoLabel = new javax.swing.JLabel();
        notePanel = new javax.swing.JPanel();
        modifyInfoButton = new javax.swing.JButton();
        modifyInfoLabel = new javax.swing.JLabel();
        deleteUserButton = new javax.swing.JButton();
        deleteUserLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        perInfoLabel1 = new javax.swing.JLabel();
        perInfoButton1 = new javax.swing.JButton();
        perInfoButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(889, 394));

        titelPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titelPanel2.setPreferredSize(new java.awt.Dimension(365, 37));

        peopleLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        peopleLogo2.setText("Logo");

        nameLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N

        arrowLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo2.setText("->");

        currentLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo2.setText("首页");

        backLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLogo2.setText("Logo");

        backLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLabel2.setText("back");

        homeLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLogo2.setText("Logo");

        homeLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLabel2.setText("home");

        exitLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLogo2.setText("Logo");

        exitLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLabel2.setText("exit");

        javax.swing.GroupLayout titelPanel2Layout = new javax.swing.GroupLayout(titelPanel2);
        titelPanel2.setLayout(titelPanel2Layout);
        titelPanel2Layout.setHorizontalGroup(
            titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleLogo2)
                .addGap(18, 18, 18)
                .addComponent(nameLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrowLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel2)
                .addGap(18, 18, 18)
                .addComponent(homeLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel2)
                .addGap(18, 18, 18)
                .addComponent(exitLogo2)
                .addGap(5, 5, 5)
                .addComponent(exitLabel2)
                .addContainerGap())
        );
        titelPanel2Layout.setVerticalGroup(
            titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLogo2)
                    .addComponent(nameLogo2)
                    .addComponent(arrowLogo2)
                    .addComponent(currentLogo2)
                    .addComponent(backLogo2)
                    .addComponent(backLabel2)
                    .addComponent(homeLogo2)
                    .addComponent(homeLabel2)
                    .addComponent(exitLogo2)
                    .addComponent(exitLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        viewInfoButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        viewInfoButton.setText("viewInfo");
        viewInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewInfoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewInfoButtonMouseExited(evt);
            }
        });
        viewInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInfoButtonActionPerformed(evt);
            }
        });

        viewInfoLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        viewInfoLabel.setForeground(new java.awt.Color(240, 240, 240));
        viewInfoLabel.setText("查看用户信息");
        viewInfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewInfoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewInfoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewInfoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewInfoLabelMouseExited(evt);
            }
        });

        addUserLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        addUserLabel.setForeground(new java.awt.Color(240, 240, 240));
        addUserLabel.setText("增添用户");
        addUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addUserLabelMouseExited(evt);
            }
        });

        addUserButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        addUserButton.setText("add");
        addUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addUserLabelMouseExited(evt);
            }
        });
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        keyLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        keyLabel.setForeground(new java.awt.Color(240, 240, 240));
        keyLabel.setText("密码重置");
        keyLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keyLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                keyLabelMouseExited(evt);
            }
        });

        perInfoButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        perInfoButton.setText("perInfo");
        perInfoButton.setToolTipText("");
        perInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                keyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                keyLabelMouseExited(evt);
            }
        });
        perInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perInfoButtonActionPerformed(evt);
            }
        });

        perInfoLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        perInfoLabel.setForeground(new java.awt.Color(240, 240, 240));
        perInfoLabel.setText("个人信息");
        perInfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perInfoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perInfoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perInfoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perInfoLabelMouseExited(evt);
            }
        });

        notePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        notePanel.setToolTipText("");

        javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
        notePanel.setLayout(notePanelLayout);
        notePanelLayout.setHorizontalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        notePanelLayout.setVerticalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        modifyInfoButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        modifyInfoButton.setText("modifyInfo");
        modifyInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyInfoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyInfoLabelMouseExited(evt);
            }
        });
        modifyInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyInfoButtonActionPerformed(evt);
            }
        });

        modifyInfoLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        modifyInfoLabel.setForeground(new java.awt.Color(240, 240, 240));
        modifyInfoLabel.setText("修改用户信息");
        modifyInfoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyInfoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyInfoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modifyInfoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modifyInfoLabelMouseExited(evt);
            }
        });

        deleteUserButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        deleteUserButton.setText("delete");
        deleteUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteUserLabelMouseExited(evt);
            }
        });
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        deleteUserLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        deleteUserLabel.setForeground(new java.awt.Color(240, 240, 240));
        deleteUserLabel.setText("删除用户");
        deleteUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteUserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteUserLabelMouseExited(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jButton1.setText("notice");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perInfoLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perInfoLabel1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        perInfoLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        perInfoLabel1.setForeground(new java.awt.Color(240, 240, 240));
        perInfoLabel1.setText("公告修改");
        perInfoLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perInfoLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                perInfoLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perInfoLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perInfoLabel1MouseExited(evt);
            }
        });

        perInfoButton1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        perInfoButton1.setText("perInfo");
        perInfoButton1.setToolTipText("");
        perInfoButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perInfoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perInfoButton1ActionPerformed(evt);
            }
        });

        perInfoButton2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        perInfoButton2.setText("perInfo");
        perInfoButton2.setToolTipText("");
        perInfoButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        perInfoButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                perInfoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                perInfoLabelMouseExited(evt);
            }
        });
        perInfoButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perInfoButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titelPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewInfoLabel)
                            .addComponent(viewInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyInfoLabel)
                            .addComponent(modifyInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(addUserLabel)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(deleteUserLabel))
                            .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(keyLabel)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(perInfoLabel))
                            .addComponent(perInfoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(perInfoLabel1))
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titelPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewInfoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modifyInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(modifyInfoLabel)
                                    .addComponent(addUserLabel)
                                    .addComponent(deleteUserLabel))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(perInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perInfoButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(keyLabel)
                                .addComponent(perInfoLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(perInfoLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInfoButtonActionPerformed
        // TODO add your handling code here:
        frame.viewGUI();
    }//GEN-LAST:event_viewInfoButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
        frame.addGUI();
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void perInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perInfoButtonActionPerformed
        // TODO add your handling code here:
        frame.resetGUI();
    }//GEN-LAST:event_perInfoButtonActionPerformed

    private void modifyInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyInfoButtonActionPerformed
        // TODO add your handling code here:
        frame.ModifyGUI();
    }//GEN-LAST:event_modifyInfoButtonActionPerformed

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        // TODO add your handling code here:
        frame.deleteGUI();
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void perInfoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perInfoButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perInfoButton1ActionPerformed

    private void perInfoButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perInfoButton2ActionPerformed
        // TODO add your handling code here:
        frame.personInfoGUI();
    }//GEN-LAST:event_perInfoButton2ActionPerformed

    private void viewInfoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInfoLabelMouseEntered
        // TODO add your handling code here:
        viewInfoLabel.setForeground(Color.red);
    }//GEN-LAST:event_viewInfoLabelMouseEntered

    private void viewInfoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInfoLabelMouseExited
        // TODO add your handling code here:
        viewInfoLabel.setForeground(Color.white);
    }//GEN-LAST:event_viewInfoLabelMouseExited

    private void viewInfoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInfoLabelMouseClicked
        // TODO add your handling code here:
        viewInfoButtonActionPerformed(null);
    }//GEN-LAST:event_viewInfoLabelMouseClicked

    private void modifyInfoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyInfoLabelMouseEntered
        // TODO add your handling code here:
        modifyInfoLabel.setForeground(Color.red);
    }//GEN-LAST:event_modifyInfoLabelMouseEntered

    private void modifyInfoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyInfoLabelMouseExited
        // TODO add your handling code here:
         modifyInfoLabel.setForeground(Color.white);
    }//GEN-LAST:event_modifyInfoLabelMouseExited

    private void modifyInfoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyInfoLabelMouseClicked
        // TODO add your handling code here:
        modifyInfoButtonActionPerformed(null);
    }//GEN-LAST:event_modifyInfoLabelMouseClicked

    private void addUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserLabelMouseEntered
        // TODO add your handling code here:
        addUserLabel.setForeground(Color.red);
    }//GEN-LAST:event_addUserLabelMouseEntered

    private void addUserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserLabelMouseExited
        // TODO add your handling code here:
        addUserLabel.setForeground(Color.white);
    }//GEN-LAST:event_addUserLabelMouseExited

    private void addUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserLabelMouseClicked
        // TODO add your handling code here:
        addUserButtonActionPerformed(null);
    }//GEN-LAST:event_addUserLabelMouseClicked

    private void viewInfoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInfoButtonMouseEntered
        // TODO add your handling code here:
         viewInfoLabel.setForeground(Color.red);
    }//GEN-LAST:event_viewInfoButtonMouseEntered

    private void viewInfoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInfoButtonMouseExited
        // TODO add your handling code here:
        viewInfoLabel.setForeground(Color.white);
    }//GEN-LAST:event_viewInfoButtonMouseExited

    private void deleteUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserLabelMouseEntered
        // TODO add your handling code here:
        deleteUserLabel.setForeground(Color.red);
    }//GEN-LAST:event_deleteUserLabelMouseEntered

    private void deleteUserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserLabelMouseExited
        // TODO add your handling code here:
        deleteUserLabel.setForeground(Color.white);
    }//GEN-LAST:event_deleteUserLabelMouseExited

    private void keyLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyLabelMouseEntered
        // TODO add your handling code here:
        keyLabel.setForeground(Color.red);
    }//GEN-LAST:event_keyLabelMouseEntered

    private void keyLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyLabelMouseExited
        // TODO add your handling code here:
        keyLabel.setForeground(Color.white);
    }//GEN-LAST:event_keyLabelMouseExited

    private void perInfoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perInfoLabelMouseEntered
        // TODO add your handling code here:
        perInfoLabel.setForeground(Color.red);
    }//GEN-LAST:event_perInfoLabelMouseEntered

    private void perInfoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perInfoLabelMouseExited
        // TODO add your handling code here:
        perInfoLabel.setForeground(Color.white);
    }//GEN-LAST:event_perInfoLabelMouseExited

    private void perInfoLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perInfoLabel1MouseEntered
        // TODO add your handling code here:
        perInfoLabel1.setForeground(Color.red);
    }//GEN-LAST:event_perInfoLabel1MouseEntered

    private void perInfoLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perInfoLabel1MouseExited
        // TODO add your handling code here:
        perInfoLabel1.setForeground(Color.white);
    }//GEN-LAST:event_perInfoLabel1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame.InformMessageGUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserLabelMouseClicked
        // TODO add your handling code here:
        deleteUserButtonActionPerformed(null);
    }//GEN-LAST:event_deleteUserLabelMouseClicked

    private void keyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyLabelMouseClicked
        // TODO add your handling code here:
        perInfoButtonActionPerformed(null);
    }//GEN-LAST:event_keyLabelMouseClicked

    private void perInfoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perInfoLabelMouseClicked
        // TODO add your handling code here:
        perInfoButton2ActionPerformed(null);
    }//GEN-LAST:event_perInfoLabelMouseClicked

    private void perInfoLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_perInfoLabel1MouseClicked
        // TODO add your handling code here:
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_perInfoLabel1MouseClicked

     public void updateName(String name){
         nameLogo2.setText(name);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JLabel addUserLabel;
    private javax.swing.JLabel arrowLogo2;
    private javax.swing.JLabel backLabel2;
    private javax.swing.JLabel backLogo2;
    private javax.swing.JLabel currentLogo2;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel deleteUserLabel;
    private javax.swing.JLabel exitLabel2;
    private javax.swing.JLabel exitLogo2;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JLabel homeLogo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JButton modifyInfoButton;
    private javax.swing.JLabel modifyInfoLabel;
    private javax.swing.JLabel nameLogo2;
    private javax.swing.JPanel notePanel;
    private javax.swing.JLabel peopleLogo2;
    private javax.swing.JButton perInfoButton;
    private javax.swing.JButton perInfoButton1;
    private javax.swing.JButton perInfoButton2;
    private javax.swing.JLabel perInfoLabel;
    private javax.swing.JLabel perInfoLabel1;
    private javax.swing.JPanel titelPanel2;
    private javax.swing.JButton viewInfoButton;
    private javax.swing.JLabel viewInfoLabel;
    // End of variables declaration//GEN-END:variables
}
