/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Administrator;

import businesslogic.processmngbl.noticebl.NoticeList;
import businesslogic.processmngbl.noticebl.NoticeReceiverFactory;
import businesslogicservice.processmngblservice.notice.NoticeReceiverService;
import businesslogicservice.processmngblservice.notice.ROLE;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import businesslogicservice.userblservice.UserLoginBLService;
import businesslogicservice.userblservice.UserLoginFactory;
import ui.JWTeacher.JWmainFrame;
import vo.uservo.UserInfoVO;

/**
 *
 * @author zili chen
 */
public class LoginPanel extends javax.swing.JPanel {

    UserLoginBLService userLogin;
    private Type type = Type.STUDENT;   //用户类型
    String t = "学生";
    String ip;//服务器的ip
    int port;//端口号
    JFrame frame;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel(JFrame frame) {
        initComponents();
        jTextArea1.setEditable(false);
        this.frame = frame;
        try {
            //rmi通信获取通知
            ip = "localhost";
            port = 1099;
            Registry registry = LocateRegistry.getRegistry(ip, port);
            UserLoginFactory ul = new UserLoginFactory();
            userLogin = ul.getUserLoginController(ip, port);
            String info = userLogin.getNotice();
            if (info != null) {
                jTextArea1.setText(info);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(LoginPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idButtonGroup = new javax.swing.ButtonGroup();
        infoPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idTextField1 = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        studentRadioButton = new javax.swing.JRadioButton();
        teacherRadioButton = new javax.swing.JRadioButton();
        adminRadioButton = new javax.swing.JRadioButton();
        deanRadioButton = new javax.swing.JRadioButton();
        insDeanRadioButton = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        notePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tip = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(720, 450));

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));

        idLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(204, 204, 204));
        idLabel.setText("ID");

        idTextField1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idTextField1.setToolTipText("ID");
        idTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        idTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField1ActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(204, 204, 204));
        passwordLabel.setText("Password");

        studentRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(studentRadioButton);
        studentRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        studentRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        studentRadioButton.setSelected(true);
        studentRadioButton.setText("学生");
        studentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRadioButtonActionPerformed(evt);
            }
        });

        teacherRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(teacherRadioButton);
        teacherRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        teacherRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        teacherRadioButton.setText("任课老师");
        teacherRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRadioButtonActionPerformed(evt);
            }
        });

        adminRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(adminRadioButton);
        adminRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        adminRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        adminRadioButton.setText("管理员");
        adminRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioButtonActionPerformed(evt);
            }
        });

        deanRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(deanRadioButton);
        deanRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        deanRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        deanRadioButton.setText("教务处老师");
        deanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deanRadioButtonActionPerformed(evt);
            }
        });

        insDeanRadioButton.setBackground(new java.awt.Color(0, 0, 0));
        idButtonGroup.add(insDeanRadioButton);
        insDeanRadioButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insDeanRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        insDeanRadioButton.setText("院教务员");
        insDeanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insDeanRadioButtonActionPerformed(evt);
            }
        });

        jPasswordField1.setToolTipText("密码");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                                .addComponent(adminRadioButton)
                                .addGap(18, 18, 18))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(studentRadioButton)
                                .addGap(32, 32, 32)))
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(deanRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(insDeanRadioButton))
                            .addComponent(teacherRadioButton)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addGap(58, 58, 58)
                        .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminRadioButton)
                    .addComponent(deanRadioButton)
                    .addComponent(insDeanRadioButton))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherRadioButton)
                    .addComponent(studentRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        notePanel.setBackground(new java.awt.Color(255, 255, 255));
        notePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        notePanel.setForeground(new java.awt.Color(255, 255, 255));
        notePanel.setPreferredSize(new java.awt.Dimension(326, 2));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("通知公告");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
        notePanel.setLayout(notePanelLayout);
        notePanelLayout.setHorizontalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notePanelLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addComponent(jScrollPane1)
        );
        notePanelLayout.setVerticalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notePanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        jButton1.setText("登陆");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("取消");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("南京大学教务系统       咨询电话：5189999 ");
        jLabel2.setToolTipText("");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("           邮件地址：xx@nju.edu.cn");

        tip.setForeground(new java.awt.Color(255, 51, 51));
        tip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tip.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel4.setFont(new java.awt.Font("宋体", 3, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("欢迎登陆");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(notePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tip, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void teacherRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRadioButtonActionPerformed
        // TODO add your handling code here:
        type = Type.TEACHER;
        t = "任课老师";
    }//GEN-LAST:event_teacherRadioButtonActionPerformed

    private void studentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadioButtonActionPerformed
        // TODO add your handling code here:
        type = Type.STUDENT;
        t = "学生";

    }//GEN-LAST:event_studentRadioButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        idTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tip.setText("");
        String ID = idTextField1.getText();
        String psw = new String(jPasswordField1.getPassword());
        UserInfoVO userVO = userLogin.login(ID, psw);
        if (userVO == null || !userVO.getType().equals(t)) {
            tip.setText("用户名或密码错误");
            return;
        }
        switch (type) {
            case STUDENT:
                break;
            case TEACHER:
                break;
            case DEAN: {
                new JWmainFrame().main(null, userVO);
                break;
            }
            case INS_DEAN:
                break;
            case ADMIN:
                frame.dispose();
                new AdminMain(userVO, ip, port).setVisible(true);
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adminRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioButtonActionPerformed
        // TODO add your handling code here:
        type = Type.ADMIN;
        t = "管理员";
    }//GEN-LAST:event_adminRadioButtonActionPerformed

    private void deanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deanRadioButtonActionPerformed
        // TODO add your handling code here:
        type = Type.DEAN;
        t = "教务处老师";
    }//GEN-LAST:event_deanRadioButtonActionPerformed

    private void insDeanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insDeanRadioButtonActionPerformed
        // TODO add your handling code here:
        type = Type.INS_DEAN;
        t = "院教务员";
    }//GEN-LAST:event_insDeanRadioButtonActionPerformed

    private void idTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField1ActionPerformed
        // TODO add your handling code here:
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_idTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_jPasswordField1ActionPerformed
    public static void main(String[] arg) {
        JFrame loginFrame = new JFrame("css-login");
        loginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        LoginPanel loginPanel = new LoginPanel(loginFrame);
        loginFrame.setSize(720, 450);
        loginFrame.setLocationRelativeTo(loginFrame.getOwner());
        loginFrame.add(loginPanel);
        loginFrame.setVisible(true);

        System.out.println("________test notice receiver____________________");
        NoticeReceiverFactory noticeReceiverFactory = new NoticeReceiverFactory();
        NoticeReceiverService nrs = noticeReceiverFactory.createReceiver(ROLE.ALL);
        NoticeList nl = nrs.getNoticeList();
        nl.printNoticeList();
        System.out.println("test_________notice ___receiver_end");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.JRadioButton deanRadioButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.ButtonGroup idButtonGroup;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField1;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JRadioButton insDeanRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel notePanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JRadioButton teacherRadioButton;
    private javax.swing.JLabel tip;
    // End of variables declaration//GEN-END:variables
}
