/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Administrator;

import enumeration.ResultMessage;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import businesslogicservice.userblservice.UserBLService;
import vo.uservo.UserInfoVO;

/**
 *
 * @author zili chen
 */
public class ModifyUserInfoPanel extends javax.swing.JPanel {

    AdminMain frame;
    UserBLService userBL;
    ArrayList<UserInfoVO> vos = new ArrayList<UserInfoVO>();
    String type = null;
    String replace = null;
    int start = 0;
    int end = -1;

    /**
     * Creates new form ModifyUserInfoPanel
     */
    public ModifyUserInfoPanel(String name, AdminMain frame, UserBLService userBL) {
        initComponents();
        nameLogo2.setText(name);
        this.frame = frame;
        this.userBL = userBL;
        vos = userBL.getUser();
        String[][] content = new String[vos.size()][4];
        for (int i = 0; i < vos.size(); i++) {

            //初始化table

            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        userListTable.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelPanel2 = new javax.swing.JPanel();
        peopleLogo2 = new javax.swing.JLabel();
        nameLogo2 = new javax.swing.JLabel();
        arrowLogo2 = new javax.swing.JLabel();
        currentLogo2 = new javax.swing.JLabel();
        backLogo2 = new javax.swing.JLabel();
        backLabel2 = new javax.swing.JLabel();
        homeLogo2 = new javax.swing.JLabel();
        homeLabel2 = new javax.swing.JLabel();
        exitLogo2 = new javax.swing.JLabel();
        exitLabel2 = new javax.swing.JLabel();
        arrowLogo3 = new javax.swing.JLabel();
        modifyLogo = new javax.swing.JLabel();
        userListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userListTable = new javax.swing.JTable();
        nameComboBox = new javax.swing.JComboBox();
        typeComboBox = new javax.swing.JComboBox();
        insComboBox = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        fromTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        modifyButton = new javax.swing.JButton();
        fromeLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        replacePanel = new javax.swing.JPanel();
        replaceLabel = new javax.swing.JLabel();
        replaceComboBox = new javax.swing.JComboBox();
        replaceToLabel = new javax.swing.JLabel();
        replaceAllButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        contentComboBox = new javax.swing.JComboBox();
        infoPanel = new javax.swing.JPanel();
        idLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        insLabel = new javax.swing.JLabel();
        birthLabel = new javax.swing.JLabel();
        identityLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        replaceToTextField1 = new javax.swing.JTextField();
        replaceToTextField2 = new javax.swing.JTextField();
        replaceToTextField3 = new javax.swing.JTextField();
        replaceToTextField4 = new javax.swing.JTextField();
        replaceToTextField5 = new javax.swing.JTextField();
        replaceToTextField6 = new javax.swing.JTextField();
        replaceToTextField7 = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        replaceToTextField8 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        titelPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titelPanel2.setPreferredSize(new java.awt.Dimension(365, 37));

        peopleLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        peopleLogo2.setText("Logo");

        nameLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLogo2.setText("name");

        arrowLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo2.setText("->");

        currentLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo2.setText("首页");
        currentLogo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        currentLogo2.setDoubleBuffered(true);
        currentLogo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentLogo2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                currentLogo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                currentLogo2MouseExited(evt);
            }
        });

        backLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLogo2.setText("Logo");

        backLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLabel2.setText("back");

        homeLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLogo2.setText("Logo");

        homeLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLabel2.setText("home");

        exitLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLogo2.setText("Logo");

        exitLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLabel2.setText("exit");

        arrowLogo3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo3.setText("->");

        modifyLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        modifyLogo.setText("modify");

        javax.swing.GroupLayout titelPanel2Layout = new javax.swing.GroupLayout(titelPanel2);
        titelPanel2.setLayout(titelPanel2Layout);
        titelPanel2Layout.setHorizontalGroup(
            titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleLogo2)
                .addGap(18, 18, 18)
                .addComponent(nameLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrowLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrowLogo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitLabel2)
                .addGap(94, 94, 94))
        );
        titelPanel2Layout.setVerticalGroup(
            titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLogo2)
                    .addComponent(nameLogo2)
                    .addComponent(arrowLogo2)
                    .addComponent(currentLogo2)
                    .addComponent(backLogo2)
                    .addComponent(backLabel2)
                    .addComponent(homeLogo2)
                    .addComponent(homeLabel2)
                    .addComponent(exitLogo2)
                    .addComponent(exitLabel2)
                    .addComponent(arrowLogo3)
                    .addComponent(modifyLogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userListPanel.setBackground(new java.awt.Color(0, 0, 0));
        userListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "用户列表", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        userListTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        userListTable.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        userListTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                int[] s = userListTable.getSelectedRows();
                if(s.length<1)
                return;
                start = s[0];
                if(s.length==1){
                    end = vos.size();
                }
                else{
                    end = s[s.length-1];
                }
                nextToModify();
            }
        });
        userListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "入学年份", "类型", "院系"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userListTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(userListTable);

        nameComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "2013", "2012", "2011", "2010" }));
        nameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameComboBoxActionPerformed(evt);
            }
        });

        typeComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "教务处老师", "院教务员", "任课老师", "学生" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        insComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "法学院", "商学院", "软件学院", "政府管理学院" }));
        insComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insComboBoxActionPerformed(evt);
            }
        });

        jTextField1.setText("请输入ID");
        jTextField1.setMinimumSize(new java.awt.Dimension(52, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(54, 25));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout userListPanelLayout = new javax.swing.GroupLayout(userListPanel);
        userListPanel.setLayout(userListPanelLayout);
        userListPanelLayout.setHorizontalGroup(
            userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(userListPanelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        userListPanelLayout.setVerticalGroup(
            userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fromTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        fromTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fromTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTextFieldActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(204, 204, 204));
        idLabel.setText("ID：");

        modifyButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        modifyButton.setText("批量修改");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        fromeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        fromeLabel.setForeground(new java.awt.Color(204, 204, 204));
        fromeLabel.setText("from");

        toLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        toLabel.setForeground(new java.awt.Color(204, 204, 204));
        toLabel.setText("to");

        toTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        toTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        toTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextFieldActionPerformed(evt);
            }
        });

        replacePanel.setBackground(new java.awt.Color(0, 0, 0));
        replacePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "替换", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        replaceLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceLabel.setForeground(new java.awt.Color(204, 204, 204));
        replaceLabel.setText("替换对象");

        replaceComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "type", "性别", "院系", "入学年份", "类型" }));
        replaceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceComboBoxActionPerformed(evt);
            }
        });

        replaceToLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToLabel.setForeground(new java.awt.Color(204, 204, 204));
        replaceToLabel.setText("替换为");

        replaceAllButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceAllButton.setText("全部替换");
        replaceAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceAllButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nextButton.setText("下一个");
        nextButton.setToolTipText("Enter");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        contentComboBox.setToolTipText("");
        contentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout replacePanelLayout = new javax.swing.GroupLayout(replacePanel);
        replacePanel.setLayout(replacePanelLayout);
        replacePanelLayout.setHorizontalGroup(
            replacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(replacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(replacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(replacePanelLayout.createSequentialGroup()
                        .addComponent(contentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(replacePanelLayout.createSequentialGroup()
                        .addGroup(replacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(replaceLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceToLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, replacePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(replacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, replacePanelLayout.createSequentialGroup()
                                .addComponent(replaceAllButton)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, replacePanelLayout.createSequentialGroup()
                                .addComponent(nextButton)
                                .addContainerGap())))))
        );
        replacePanelLayout.setVerticalGroup(
            replacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(replacePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(replaceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(replaceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(replaceToLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(replaceAllButton)
                .addGap(72, 72, 72)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));
        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "具体信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        idLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel1.setForeground(new java.awt.Color(204, 204, 204));
        idLabel1.setText("学(工)号");

        nameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel.setText("姓名");

        typeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(204, 204, 204));
        typeLabel.setText("类型");

        insLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insLabel.setForeground(new java.awt.Color(204, 204, 204));
        insLabel.setText("院系");

        birthLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        birthLabel.setForeground(new java.awt.Color(204, 204, 204));
        birthLabel.setText("出生日期");

        identityLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        identityLabel.setForeground(new java.awt.Color(204, 204, 204));
        identityLabel.setText("身份证号");

        sexLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(204, 204, 204));
        sexLabel.setText("性别");

        replaceToTextField1.setEditable(false);
        replaceToTextField1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField1ActionPerformed(evt);
            }
        });

        replaceToTextField2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField2ActionPerformed(evt);
            }
        });

        replaceToTextField3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField3ActionPerformed(evt);
            }
        });

        replaceToTextField4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField4ActionPerformed(evt);
            }
        });

        replaceToTextField5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField5ActionPerformed(evt);
            }
        });

        replaceToTextField6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField6ActionPerformed(evt);
            }
        });

        replaceToTextField7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField7ActionPerformed(evt);
            }
        });

        yearLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(204, 204, 204));
        yearLabel.setText("入学年份");

        replaceToTextField8.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        replaceToTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        replaceToTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceToTextField8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1)
                            .addComponent(nameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceToTextField2)
                            .addComponent(replaceToTextField1)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(sexLabel)
                        .addGap(42, 42, 42)
                        .addComponent(replaceToTextField3))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthLabel)
                            .addComponent(typeLabel)
                            .addComponent(insLabel)
                            .addComponent(identityLabel))
                        .addGap(14, 14, 14)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(replaceToTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(replaceToTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(replaceToTextField5)
                            .addComponent(replaceToTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(yearLabel)
                        .addGap(15, 15, 15)
                        .addComponent(replaceToTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel1)
                    .addComponent(replaceToTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(replaceToTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceToTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceToTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceToTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceToTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthLabel))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceToTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identityLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceToTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titelPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(idLabel)
                        .addGap(18, 18, 18)
                        .addComponent(fromeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(modifyButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(replacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(titelPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel)
                            .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fromeLabel)
                            .addComponent(toLabel)
                            .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(399, 399, 399))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void replaceToTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField6ActionPerformed
        // TODO add your handling code here:
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_replaceToTextField6ActionPerformed

    private void replaceToTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField7ActionPerformed
        // TODO add your handling code here:
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_replaceToTextField7ActionPerformed

    private void replaceAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceAllButtonActionPerformed
        // TODO add your handling code here:
        if ((type.equals("性别"))) {
            for (UserInfoVO vo : vos) {
                vo.setSex(replace);
            }
        } else if (type.equals("院系")) {
            for (UserInfoVO vo : vos) {
                vo.setDepart(replace);
            }
        } else if (type.equals("入学年份")) {
            for (UserInfoVO vo : vos) {
                vo.setYearIn(replace);
            }
        } else if (type.equals("类型")) {
            for (UserInfoVO vo : vos) {
                vo.setType(replace);
            }
        }
        //替换后，跟新combobox
        String[][] content = new String[vos.size()][4];
        for (int i = 0; i < vos.size(); i++) {
            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        userListTable.setModel(model);
        if (userBL.changeUserInfo() == ResultMessage.SUCCESS) {
            JOptionPane.showMessageDialog(this, "修改成功！");
        } else {
            JOptionPane.showMessageDialog(this, "修改失败！");
        }
    }//GEN-LAST:event_replaceAllButtonActionPerformed

    private void replaceToTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceToTextField1ActionPerformed

    private void replaceToTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField8ActionPerformed
        // TODO add your handling code here:
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_replaceToTextField8ActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if (end == -1) {
            end = vos.size();
        }
        nextToModify();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void currentLogo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLogo2MouseEntered
        // TODO add your handling code here:
        currentLogo2.setForeground(Color.red);
    }//GEN-LAST:event_currentLogo2MouseEntered

    private void currentLogo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLogo2MouseExited
        // TODO add your handling code here:
        currentLogo2.setForeground(Color.black);
    }//GEN-LAST:event_currentLogo2MouseExited

    private void replaceToTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField4ActionPerformed
        // TODO add your handling code here:
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_replaceToTextField4ActionPerformed

    private void replaceToTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField5ActionPerformed
        // TODO add your handling code here:
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_replaceToTextField5ActionPerformed

    private void currentLogo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLogo2MouseClicked
        // TODO add your handling code here:
        frame.mainGUI();
    }//GEN-LAST:event_currentLogo2MouseClicked

    private void insComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insComboBoxActionPerformed
        // TODO add your handling code here:
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_insComboBoxActionPerformed

    private void nameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameComboBoxActionPerformed
        // TODO add your handling code here:
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_nameComboBoxActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        jTextField1.setText("");
        System.out.print(replace);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        String ID = jTextField1.getText();
        if (ID.equals("") || ID.equals("请输入ID")) {
            ID = null;
        }
        String year = (String) nameComboBox.getSelectedItem();
        String type = (String) typeComboBox.getSelectedItem();
        String ins = (String) insComboBox.getSelectedItem();
        vos = userBL.getUser(ID, year, type, ins);
        String[][] content = new String[vos.size()][7];
        for (int i = 0; i < vos.size(); i++) {
            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        userListTable.setModel(model);

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void fromTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTextFieldActionPerformed
        // TODO add your handling code here:
        String fromID = fromTextField.getText();
        String toID = toTextField.getText();
        vos = userBL.getUser(fromID, toID);
        String[][] content = new String[vos.size()][4];
        for (int i = 0; i < vos.size(); i++) {
            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        userListTable.setModel(model);

    }//GEN-LAST:event_fromTextFieldActionPerformed

    private void toTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextFieldActionPerformed
        // TODO add your handling code here:
        fromTextFieldActionPerformed(evt);
    }//GEN-LAST:event_toTextFieldActionPerformed

    private void replaceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceComboBoxActionPerformed
        // TODO add your handling code here:
        type = (String) replaceComboBox.getSelectedItem();
        if (type.equals("type")) {
            contentComboBox.removeAllItems();
        } else if (type.equals("性别")) {
            contentComboBox.removeAllItems();
            contentComboBox.addItem("男");
            contentComboBox.addItem("女");
        } else if (type.equals("院系")) {
            contentComboBox.removeAllItems();
            contentComboBox.addItem("软件学院");
            contentComboBox.addItem("商学院");
            contentComboBox.addItem("政府管理学院");
            contentComboBox.addItem("医学院");
        } else if (type.equals("类型")) {
            contentComboBox.removeAllItems();
            contentComboBox.addItem("学生");
            contentComboBox.addItem("任课老师");
            contentComboBox.addItem("院教务员");
            contentComboBox.addItem("教务处老师");
        } else if (type.equals("入学年份")) {
            contentComboBox.removeAllItems();
            contentComboBox.addItem("2010");
            contentComboBox.addItem("2011");
            contentComboBox.addItem("2012");
            contentComboBox.addItem("2013");
        }
    }//GEN-LAST:event_replaceComboBoxActionPerformed

    private void contentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentComboBoxActionPerformed
        // TODO add your handling code here:
        replace = (String) contentComboBox.getSelectedItem();
    }//GEN-LAST:event_contentComboBoxActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        start = 0;
        end = vos.size();
        fromTextFieldActionPerformed(null);
        nextToModify();
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void replaceToTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField2ActionPerformed
        // TODO add your handling code here:
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_replaceToTextField2ActionPerformed

    private void replaceToTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceToTextField3ActionPerformed
        // TODO add your handling code here:
        nextButtonActionPerformed(evt);
    }//GEN-LAST:event_replaceToTextField3ActionPerformed

    public void nextToModify() {

        if (start < end) {
            if (replaceToTextField1.getText() != null && !replaceToTextField1.getText().equals("") && start > 0) {
                UserInfoVO vo = vos.get(start - 1);
                if (vo.getID().equals(replaceToTextField1.getText())) {
                    vo.setName(replaceToTextField2.getText());
                    vo.setSex(replaceToTextField3.getText());
                    vo.setType(replaceToTextField4.getText());
                    vo.setDepart(replaceToTextField5.getText());
                    vo.setGrade(replaceToTextField6.getText());
                    vo.setIdentification(replaceToTextField7.getText());
                    vo.setYearIn(replaceToTextField8.getText());
                    userListTable.setValueAt(vo.getYearIn(), start - 1, 1);
                    userListTable.setValueAt(vo.getType(), start - 1, 2);
                    userListTable.setValueAt(vo.getDepart(), start - 1, 3);
                }
            }
            UserInfoVO vo = vos.get(start++);
            replaceToTextField1.setText(vo.getID());
            replaceToTextField2.setText(vo.getName());
            replaceToTextField3.setText(vo.getSex());
            replaceToTextField4.setText(vo.getType());
            replaceToTextField5.setText(vo.getDepart());
            replaceToTextField6.setText(vo.getGrade());
            replaceToTextField7.setText(vo.getIdentification());
            replaceToTextField8.setText(vo.getYearIn());
        } else {
            int result = JOptionPane.showConfirmDialog(this, "提交修改", null, JOptionPane.YES_NO_OPTION);
            switch (result) {
                case JOptionPane.YES_OPTION:
                    if (userBL.changeUserInfo() == ResultMessage.SUCCESS) {
                        JOptionPane.showMessageDialog(this, "修改成功！");
                    } else {
                        JOptionPane.showMessageDialog(this, "修改失败！");
                    }
                    break;
                case JOptionPane.NO_OPTION:
                    userBL.getUser();
                    jTextField1ActionPerformed(null);
                    userListTable.invalidate();
            }
            start = 0;
            end = -1;
        }
    }
     /**
     * 更新此界面
     */
    public void update(){
        fromTextField.setText("");
        toTextField.setText("");
        replaceComboBox.setSelectedIndex(0);
         jTextField1.setText("请输入ID");
        nameComboBox.setSelectedIndex(0);
        typeComboBox.setSelectedIndex(0);
        insComboBox.setSelectedIndex(0);
        
        replaceToTextField1.setText("");
            replaceToTextField2.setText("");
            replaceToTextField3.setText("");
            replaceToTextField4.setText("");
            replaceToTextField5.setText("");
            replaceToTextField6.setText("");
            replaceToTextField7.setText("");
            replaceToTextField8.setText("");
            
        replaceComboBoxActionPerformed(null);
         vos = userBL.getUser();
        String[][] content = new String[vos.size()][4];
        for (int i = 0; i < vos.size(); i++) {

            //初始化table

            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        userListTable.setModel(model);
        

    }
      public void updateName(String name){
         nameLogo2.setText(name);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrowLogo2;
    private javax.swing.JLabel arrowLogo3;
    private javax.swing.JLabel backLabel2;
    private javax.swing.JLabel backLogo2;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JComboBox contentComboBox;
    private javax.swing.JLabel currentLogo2;
    private javax.swing.JLabel exitLabel2;
    private javax.swing.JLabel exitLogo2;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JLabel fromeLabel;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JLabel homeLogo2;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel identityLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JComboBox insComboBox;
    private javax.swing.JLabel insLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modifyButton;
    private javax.swing.JLabel modifyLogo;
    private javax.swing.JComboBox nameComboBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLogo2;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel peopleLogo2;
    private javax.swing.JButton replaceAllButton;
    private javax.swing.JComboBox replaceComboBox;
    private javax.swing.JLabel replaceLabel;
    private javax.swing.JPanel replacePanel;
    private javax.swing.JLabel replaceToLabel;
    private javax.swing.JTextField replaceToTextField1;
    private javax.swing.JTextField replaceToTextField2;
    private javax.swing.JTextField replaceToTextField3;
    private javax.swing.JTextField replaceToTextField4;
    private javax.swing.JTextField replaceToTextField5;
    private javax.swing.JTextField replaceToTextField6;
    private javax.swing.JTextField replaceToTextField7;
    private javax.swing.JTextField replaceToTextField8;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JPanel titelPanel2;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField toTextField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JPanel userListPanel;
    private javax.swing.JTable userListTable;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
