/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Administrator;

import enumeration.ResultMessage;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import businesslogicservice.userblservice.UserBLService;
import vo.uservo.UserInfoVO;

/**
 *
 * @author zili chen
 */
public class ResetKeyPanel extends javax.swing.JPanel {
AdminMain frame;
UserBLService userBL;
ArrayList<UserInfoVO> vos;
int i=-1;
    /**
     * Creates new form ResetKeyPanel
     */
    public ResetKeyPanel(String name,AdminMain frame,UserBLService userBL) {
        initComponents();
        this.frame = frame;
        this.userBL= userBL;
        nameLogo2.setText(name);
        
         vos = userBL.getUser();
        String[][] content = new String[vos.size()][4];
        for(int i=0;i<vos.size();i++){

        //初始化table
        
            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
             return false;
            }
        };
        userListTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelPanel2 = new javax.swing.JPanel();
        peopleLogo2 = new javax.swing.JLabel();
        nameLogo2 = new javax.swing.JLabel();
        arrowLogo2 = new javax.swing.JLabel();
        currentLogo2 = new javax.swing.JLabel();
        backLogo2 = new javax.swing.JLabel();
        backLabel2 = new javax.swing.JLabel();
        homeLogo2 = new javax.swing.JLabel();
        homeLabel2 = new javax.swing.JLabel();
        exitLogo2 = new javax.swing.JLabel();
        exitLabel2 = new javax.swing.JLabel();
        arrowLogo3 = new javax.swing.JLabel();
        currentLogo3 = new javax.swing.JLabel();
        userListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userListTable = new javax.swing.JTable();
        yearComboBox = new javax.swing.JComboBox();
        typeComboBox = new javax.swing.JComboBox();
        insComboBox = new javax.swing.JComboBox();
        IDTextField1 = new javax.swing.JTextField();
        initialButton = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        idLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        insLabel = new javax.swing.JLabel();
        birthLabel = new javax.swing.JLabel();
        identityLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        idLabel2 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        sexLabel2 = new javax.swing.JLabel();
        typeLabel2 = new javax.swing.JLabel();
        insLabel2 = new javax.swing.JLabel();
        birthLabel2 = new javax.swing.JLabel();
        identityLabel2 = new javax.swing.JLabel();
        yearLabel1 = new javax.swing.JLabel();
        yearLabel2 = new javax.swing.JLabel();
        setKeyButton = new javax.swing.JButton();
        newKeyLabel = new javax.swing.JLabel();
        newKeyLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fromeTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        newPasswordField1 = new javax.swing.JPasswordField();
        newPasswordField2 = new javax.swing.JPasswordField();
        tipLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setDoubleBuffered(false);

        titelPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titelPanel2.setPreferredSize(new java.awt.Dimension(365, 37));

        peopleLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        peopleLogo2.setText("Logo");

        nameLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLogo2.setText("name");

        arrowLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo2.setText("->");

        currentLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo2.setText("首页");
        currentLogo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        currentLogo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentLogo2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                currentLogo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                currentLogo2MouseExited(evt);
            }
        });

        backLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLogo2.setText("Logo");

        backLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLabel2.setText("back");

        homeLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLogo2.setText("Logo");

        homeLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLabel2.setText("home");

        exitLogo2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLogo2.setText("Logo");

        exitLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLabel2.setText("exit");

        arrowLogo3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo3.setText("->");

        currentLogo3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo3.setText("reset");

        javax.swing.GroupLayout titelPanel2Layout = new javax.swing.GroupLayout(titelPanel2);
        titelPanel2.setLayout(titelPanel2Layout);
        titelPanel2Layout.setHorizontalGroup(
            titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleLogo2)
                .addGap(18, 18, 18)
                .addComponent(nameLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrowLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrowLogo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentLogo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 425, Short.MAX_VALUE)
                .addComponent(backLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel2)
                .addGap(18, 18, 18)
                .addComponent(homeLogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel2)
                .addGap(18, 18, 18)
                .addComponent(exitLogo2)
                .addGap(5, 5, 5)
                .addComponent(exitLabel2)
                .addContainerGap())
        );
        titelPanel2Layout.setVerticalGroup(
            titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titelPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLogo2)
                    .addComponent(nameLogo2)
                    .addComponent(arrowLogo2)
                    .addComponent(currentLogo2)
                    .addComponent(backLogo2)
                    .addComponent(backLabel2)
                    .addComponent(homeLogo2)
                    .addComponent(homeLabel2)
                    .addComponent(exitLogo2)
                    .addComponent(exitLabel2)
                    .addComponent(arrowLogo3)
                    .addComponent(currentLogo3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userListPanel.setBackground(new java.awt.Color(0, 0, 0));
        userListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "用户列表", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        userListTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        userListTable.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        userListTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                int s[] = userListTable.getSelectedRows();
                if(s.length<1)
                return;
                if(s[0]>=0){
                    i = s[0];
                    tableValueChanged(s[0]);
                }
            }
        });
        userListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "入学年份", "类型", "院系"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userListTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(userListTable);

        yearComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "2013", "2012", "2011" }));
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        typeComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "教务处老师", "院教务员", "任课老师", "学生" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        insComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "法学院", "商学院", "软件学院", "政府管理学院" }));
        insComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insComboBoxActionPerformed(evt);
            }
        });

        IDTextField1.setText("请输入ID");
        IDTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextField1ActionPerformed(evt);
            }
        });
        IDTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDTextField1FocusGained(evt);
            }
        });

        javax.swing.GroupLayout userListPanelLayout = new javax.swing.GroupLayout(userListPanel);
        userListPanel.setLayout(userListPanelLayout);
        userListPanelLayout.setHorizontalGroup(
            userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(userListPanelLayout.createSequentialGroup()
                        .addComponent(IDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insComboBox, 0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        userListPanelLayout.setVerticalGroup(
            userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        initialButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        initialButton.setText("初始化所有密码");
        initialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialButtonActionPerformed(evt);
            }
        });

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));
        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "具体信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        idLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel1.setForeground(new java.awt.Color(204, 204, 204));
        idLabel1.setText("学(工)号");

        nameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel.setText("姓名");

        typeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(204, 204, 204));
        typeLabel.setText("类型");

        insLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insLabel.setForeground(new java.awt.Color(204, 204, 204));
        insLabel.setText("院系");

        birthLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        birthLabel.setForeground(new java.awt.Color(204, 204, 204));
        birthLabel.setText("出生日期");

        identityLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        identityLabel.setForeground(new java.awt.Color(204, 204, 204));
        identityLabel.setText("身份证号");

        sexLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(204, 204, 204));
        sexLabel.setText("性别");

        idLabel2.setBackground(new java.awt.Color(0, 0, 0));
        idLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel2.setForeground(new java.awt.Color(204, 204, 204));
        idLabel2.setText("XX");

        nameLabel2.setBackground(new java.awt.Color(0, 0, 0));
        nameLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel2.setText("XX");

        sexLabel2.setBackground(new java.awt.Color(0, 0, 0));
        sexLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sexLabel2.setForeground(new java.awt.Color(204, 204, 204));
        sexLabel2.setText("XX");

        typeLabel2.setBackground(new java.awt.Color(0, 0, 0));
        typeLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeLabel2.setForeground(new java.awt.Color(204, 204, 204));
        typeLabel2.setText("XX");

        insLabel2.setBackground(new java.awt.Color(0, 0, 0));
        insLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insLabel2.setForeground(new java.awt.Color(204, 204, 204));
        insLabel2.setText("XX");

        birthLabel2.setBackground(new java.awt.Color(0, 0, 0));
        birthLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        birthLabel2.setForeground(new java.awt.Color(204, 204, 204));
        birthLabel2.setText("XX");

        identityLabel2.setBackground(new java.awt.Color(0, 0, 0));
        identityLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        identityLabel2.setForeground(new java.awt.Color(204, 204, 204));
        identityLabel2.setText("XX");

        yearLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        yearLabel1.setForeground(new java.awt.Color(204, 204, 204));
        yearLabel1.setText("入学年份");

        yearLabel2.setBackground(new java.awt.Color(0, 0, 0));
        yearLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        yearLabel2.setForeground(new java.awt.Color(204, 204, 204));
        yearLabel2.setText("XX");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(identityLabel)
                        .addGap(18, 18, 18)
                        .addComponent(identityLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(birthLabel)
                        .addGap(18, 18, 18)
                        .addComponent(birthLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1)
                            .addComponent(nameLabel)
                            .addComponent(sexLabel)
                            .addComponent(typeLabel)
                            .addComponent(insLabel))
                        .addGap(18, 18, 18)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(yearLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(yearLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel1)
                    .addComponent(idLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameLabel2))
                .addGap(22, 22, 22)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel)
                    .addComponent(sexLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insLabel)
                    .addComponent(insLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthLabel)
                    .addComponent(birthLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identityLabel)
                    .addComponent(identityLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel1)
                    .addComponent(yearLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setKeyButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        setKeyButton.setText("确认");
        setKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setKeyButtonActionPerformed(evt);
            }
        });

        newKeyLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        newKeyLabel.setForeground(new java.awt.Color(204, 204, 204));
        newKeyLabel.setText("新密码");

        newKeyLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        newKeyLabel2.setForeground(new java.awt.Color(204, 204, 204));
        newKeyLabel2.setText("新密码确认");

        cancelButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cancelButton.setText("取消");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Frome:");

        fromeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromeTextFieldActionPerformed(evt);
            }
        });

        toTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("to");

        newPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordField1ActionPerformed(evt);
            }
        });

        newPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordField2ActionPerformed(evt);
            }
        });

        tipLabel.setForeground(new java.awt.Color(255, 51, 51));
        tipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(initialButton))
                    .addComponent(userListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(newPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newKeyLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newKeyLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(setKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(titelPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titelPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(newKeyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(newPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(newKeyLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(setKeyButton)
                        .addGap(30, 30, 30)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(15, 15, 15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fromeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                        .addGap(12, 12, 12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(toTextField)
                                        .addGap(12, 12, 12))
                                    .addComponent(initialButton)
                                    .addComponent(jLabel2))
                                .addComponent(userListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(306, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void currentLogo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLogo2MouseClicked
        // TODO add your handling code here:
        frame.mainGUI();
    }//GEN-LAST:event_currentLogo2MouseClicked

    private void currentLogo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLogo2MouseEntered
        // TODO add your handling code here:
        currentLogo2.setForeground(Color.red);
    }//GEN-LAST:event_currentLogo2MouseEntered

    private void currentLogo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLogo2MouseExited
        // TODO add your handling code here:
        currentLogo2.setForeground(Color.black
                );
    }//GEN-LAST:event_currentLogo2MouseExited

    private void fromeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromeTextFieldActionPerformed
        // TODO add your handling code here:
             String fromID = fromeTextField.getText();
        String toID = toTextField.getText();
        vos = userBL.getUser(fromID,toID);
        String[][] content = new String[vos.size()][4];
        for(int i=0;i<vos.size();i++){
            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
             return false;
            }
        };
        userListTable.setModel(model);
    }//GEN-LAST:event_fromeTextFieldActionPerformed

    private void newPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordField1ActionPerformed
        // TODO add your handling code here:
        setKeyButtonActionPerformed(evt);
    }//GEN-LAST:event_newPasswordField1ActionPerformed

    private void newPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordField2ActionPerformed
        // TODO add your handling code here:
        setKeyButtonActionPerformed(evt);
    }//GEN-LAST:event_newPasswordField2ActionPerformed

    private void toTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTextFieldActionPerformed
        // TODO add your handling code here:
        fromeTextFieldActionPerformed(evt);
    }//GEN-LAST:event_toTextFieldActionPerformed

    private void IDTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextField1FocusGained
        // TODO add your handling code here:
        IDTextField1.setText("");
    }//GEN-LAST:event_IDTextField1FocusGained

    private void IDTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextField1ActionPerformed
        // TODO add your handling code here:
          String ID = IDTextField1.getText();
        if(ID.equals("")||ID.equals("请输入ID")){
            ID = null;
        }
        String year = (String) yearComboBox.getSelectedItem();
        String type = (String) typeComboBox.getSelectedItem();
        String ins = (String) insComboBox.getSelectedItem();
        vos = userBL.getUser(ID, year, type, ins);
         String[][] content = new String[vos.size()][7];
        for(int i=0;i<vos.size();i++){
            content[i] = vos.get(i).getModifyInfo();
        }
        String[] head = UserInfoVO.getModifyHeader();
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
             return false;
            }
        };
        userListTable.setModel(model);
    }//GEN-LAST:event_IDTextField1ActionPerformed

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed
        // TODO add your handling code here:
        IDTextField1ActionPerformed(evt);
    }//GEN-LAST:event_yearComboBoxActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
        IDTextField1ActionPerformed(evt);
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void insComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insComboBoxActionPerformed
        // TODO add your handling code here:
        IDTextField1ActionPerformed(evt);
    }//GEN-LAST:event_insComboBoxActionPerformed

    private void setKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setKeyButtonActionPerformed
        // TODO add your handling code here:
        String s1 = new String(newPasswordField1.getPassword());
        String s2 = new String(newPasswordField2.getPassword());
        if(!s1.equals(s2)){
            tipLabel.setText("两次密码不一致");
            return;
        }
        else{
            if(i!=-1){
                UserInfoVO v = vos.get(i);
                v.setPsw(s1);
            if(userBL.changeUserInfo()==ResultMessage.SUCCESS){
                JOptionPane.showConfirmDialog(frame, "修改成功", null, JOptionPane.OK_OPTION);
            }
            else{
                JOptionPane.showConfirmDialog(frame, "修改失败", null, JOptionPane.OK_OPTION);
            }
            i=-1;
            }
        }
    }//GEN-LAST:event_setKeyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        newPasswordField1.setText("");
        newPasswordField2.setText("");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void initialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialButtonActionPerformed
        // TODO add your handling code here:
        for(UserInfoVO v:vos){
            v.setPsw(v.getID());
        }
         if(userBL.changeUserInfo()==ResultMessage.SUCCESS){
                JOptionPane.showConfirmDialog(frame, "修改成功", null, JOptionPane.OK_OPTION);
            }
            else{
                JOptionPane.showConfirmDialog(frame, "修改失败", null, JOptionPane.OK_OPTION);
            }
    }//GEN-LAST:event_initialButtonActionPerformed

    private void tableValueChanged(int i){
        UserInfoVO v = vos.get(i);
        idLabel2.setText(v.getID());
        nameLabel2.setText(v.getName());
        typeLabel2.setText(v.getType());
        insLabel2.setText(v.getDepart());
        identityLabel2.setText(v.getIdentification());
        birthLabel2.setText(v.getGrade());
        yearLabel2.setText(v.getYearIn());
        sexLabel2.setText(v.getSex());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTextField1;
    private javax.swing.JLabel arrowLogo2;
    private javax.swing.JLabel arrowLogo3;
    private javax.swing.JLabel backLabel2;
    private javax.swing.JLabel backLogo2;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JLabel birthLabel2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentLogo2;
    private javax.swing.JLabel currentLogo3;
    private javax.swing.JLabel exitLabel2;
    private javax.swing.JLabel exitLogo2;
    private javax.swing.JTextField fromeTextField;
    private javax.swing.JLabel homeLabel2;
    private javax.swing.JLabel homeLogo2;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JLabel identityLabel;
    private javax.swing.JLabel identityLabel2;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton initialButton;
    private javax.swing.JComboBox insComboBox;
    private javax.swing.JLabel insLabel;
    private javax.swing.JLabel insLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLogo2;
    private javax.swing.JLabel newKeyLabel;
    private javax.swing.JLabel newKeyLabel2;
    private javax.swing.JPasswordField newPasswordField1;
    private javax.swing.JPasswordField newPasswordField2;
    private javax.swing.JLabel peopleLogo2;
    private javax.swing.JButton setKeyButton;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel sexLabel2;
    private javax.swing.JLabel tipLabel;
    private javax.swing.JPanel titelPanel2;
    private javax.swing.JTextField toTextField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeLabel2;
    private javax.swing.JPanel userListPanel;
    private javax.swing.JTable userListTable;
    private javax.swing.JComboBox yearComboBox;
    private javax.swing.JLabel yearLabel1;
    private javax.swing.JLabel yearLabel2;
    // End of variables declaration//GEN-END:variables
}
