/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Administrator;

import java.awt.BorderLayout;
import java.awt.Container;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author 天
 */
public class WaitPanelj extends javax.swing.JFrame {
    boolean b=true;
    Thread t;
    ImageIcon image;
      Container cp;
       JLabel imgLabel;
    /**
     * Creates new form WaitPanelj
     */
    public WaitPanelj() {
        initComponents();
        image = new ImageIcon("C:\\Users\\Administrator\\Desktop\\images\\1.gif");
        imgLabel = new JLabel(image);
        imgLabel.setBounds(0, 0, this.getWidth(), this.getHeight());
        this.getLayeredPane().add(imgLabel,new Integer(Integer.MIN_VALUE));
         cp = this.getContentPane();
        cp.setLayout(new BorderLayout());
        JButton but = new JButton("hui");
        cp.add(but,"North");
        ((JPanel)cp).setOpaque(false);
        setLocationRelativeTo(this.getOwner());
        imgLabel.setVisible(true);
        setVisible(true);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       new WaitPanelj();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

 
    public void run() {
        
        int i=1;
        while(b){
            try {
                Thread.sleep(500);
                i++;
                image = new ImageIcon("F:\\picture\\苏州\\WP_20130701_00"+i+".jpg");
                imgLabel.setIcon(image);
            } catch (InterruptedException ex) {
                Logger.getLogger(WaitPanelj.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        dispose();
    }
}
