/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Admin;

import ui.Library.MyFont;
import businesslogicservice.userblservice.UserBLService;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import static ui.Admin.AdminMain.card;
import ui.Library.LogoButton;
import ui.Library.Navigation;
import vo.uservo.UserInfoVO;

/**
 *
 * @author zili Chen
 */
public class ViewInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInfoPanel
     */
    public ViewInfoPanel(String name,AdminMain frame,UserBLService userBL) {
        initComponents();
        /*逻辑-任天*/
        vos = new ArrayList<UserInfoVO>();
        /*GUI-主panel*/
        setOpaque(false);
        navPanel.setOpaque(false);
        /*GUI-导航*/
        navigation = new Navigation(navPanel,card,AdminMain.contain,"mainP");
        /*GUI-输入框和下拉框*/
        font = new MyFont();
        idTextField = new JTextField();
        add(idTextField,0,0);
        idTextField.setBounds(50,70,150,30);
        idTextField.setFont(font.getFont());
        yearComboBox = new JComboBox();
        identityComboBox = new JComboBox();
        insComboBox = new JComboBox();
        add(yearComboBox,0,0);
        add(identityComboBox,0,0);
        add(insComboBox,0,0);
        yearComboBox.setBounds(300,70,180,30);
        identityComboBox.setBounds(500,70,180,30);
        insComboBox.setBounds(700,70,180,30);
        searchP = new ImageIcon("src/Picture/search.gif");
        searchButton = new JButton(searchP);
        add(searchButton,0,0);
        searchButton.setBounds(210,55,searchP.getIconWidth(),searchP.getIconHeight());
        searchButton.setContentAreaFilled(false);
        /*逻辑-任天*/
        this.name = name;
        this.frame = frame;
        this.userBL = userBL;
    }

    public void update() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();

        navPanel.setBackground(new java.awt.Color(51, 255, 102));

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 364, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel navPanel;
    // End of variables declaration//GEN-END:variables
    /*GUI-导航*/
    private Navigation navigation;
    /*GUI-输入框和下拉框*/
    private MyFont font;
    private JTextField idTextField;
    private JComboBox yearComboBox;//入学年份
    private JComboBox identityComboBox;//类型:教务处老师/4个
    private JComboBox insComboBox;//院系
    private ImageIcon searchP;
    private JButton searchButton;
    /*逻辑-任天*/
    private String name;
    private AdminMain frame;
    private UserBLService userBL;
    private ArrayList<UserInfoVO> vos;
}
