/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

import ui.YJWTeacher.*;
import businesslogicservice.courseblservice.CourseBLService;
import businesslogicservice.courseblservice.CourseOperationFactory;
import enumeration.ResultMessage;
import java.awt.FileDialog;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import vo.coursevo.CourseVO;
import vo.uservo.UserInfoVO;

/**
 *
 * @author 天
 */
public class AddCoursePanel extends javax.swing.JPanel {
String ip;
int port;
CourseBLService courseBL;
ArrayList<CourseVO> vos=new ArrayList<CourseVO>();
CourseOperationFactory factory = new CourseOperationFactory();
DefaultListModel listModel = new DefaultListModel();
JFrame frame;
boolean isEdit = false;
CourseVO v;
    /**
     * Creates new form AddCoursePanel
     */
    public AddCoursePanel(String ip,int port,JFrame frame) {
        this.ip = ip;
        this.port = port;
        this.frame = frame;
        initComponents();
        
        courseBL = factory.createCourseBL();
        String[] s=courseBL.jgetAllTerms();
        for(String str:s){
            listModel.addElement(str);
        }
        termList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        termList = new javax.swing.JList();
        addTermButton = new javax.swing.JButton();
        courseButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        openButton = new javax.swing.JButton();
        commitButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        termList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        termList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                termListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(termList);

        addTermButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        addTermButton.setText("添加新学期");
        addTermButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTermButtonActionPerformed(evt);
            }
        });

        courseButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        courseButton.setText("将课程导入到新学期");
        courseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseButtonActionPerformed(evt);
            }
        });

        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(courseTable);
        courseTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                int s[] = courseTable.getSelectedRows();
                if(s.length<1)
                return;
                if(s[0]>=0){
                    TableValueChanged(s[0]);

                }
            }
        });

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel1.setText("从文件中添加");

        fileTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        fileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileTextFieldActionPerformed(evt);
            }
        });

        openButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        openButton.setText("打开");
        openButton.setEnabled(false);
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        commitButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        commitButton.setText("提交");
        commitButton.setEnabled(false);
        commitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("删除");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyButton.setText("修改");
        modifyButton.setEnabled(false);
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        addButton.setText("添加");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("刷新");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(addTermButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modifyButton)
                            .addComponent(deleteButton)
                            .addComponent(addButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateButton)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(openButton)
                        .addGap(38, 38, 38)
                        .addComponent(commitButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(openButton)
                                .addComponent(commitButton)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTermButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(courseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifyButton)
                            .addComponent(updateButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void termListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_termListValueChanged
        // TODO add your handling code here:
        String term=(String) termList.getSelectedValue();
        if(term==null){
            return;
        }
        if(term.equals((String)listModel.lastElement())){
            openButton.setEnabled(true);
            commitButton.setEnabled(true);
            addButton.setEnabled(true);
            isEdit = true;
        }
        else{
            isEdit = false;
            addButton.setEnabled(false);
            openButton.setEnabled(false);
            commitButton.setEnabled(false);
            
        }
                    deleteButton.setEnabled(false);
             modifyButton.setEnabled(false);
       courseBL = factory.createCourseBL(term);
       vos = courseBL.jobserveAllCour();
       updateTable();
    }//GEN-LAST:event_termListValueChanged

    /**
     * 开设新课程
     * @param evt 
     */
    private void addTermButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTermButtonActionPerformed
        // TODO add your handling code here:
        String s = (String) listModel.lastElement();
        String[] ts = s.split("-");
        int year1 = Integer.parseInt(ts[0]);
        int month1 = Integer.parseInt(ts[1]);
        
        Calendar c = Calendar.getInstance();
        int year = c.get(Calendar.YEAR);
        int month = c.get(Calendar.MONTH);
        String newTerm;
        if(month<2){
            newTerm = (year-1)+"-"+2;
        }
        else if(month<8){
            newTerm = year+"-"+1;
        }
        else{
            newTerm = year+"-"+2;
        }
        if(newTerm.equals(s)){
            JOptionPane.showConfirmDialog(this, "时间未到", null, JOptionPane.OK_OPTION);
            return;
        }
        else{
            listModel.addElement(newTerm);
           // courseBL = factory.createCourseBL();   //创建文件
            courseBL.jcreateTerm(newTerm);
            courseButton.setEnabled(true);
        }
    }//GEN-LAST:event_addTermButtonActionPerformed

    private void courseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseButtonActionPerformed
        // TODO add your handling code here:
         //courseBL = factory.createCourseBL((String)listModel.lastElement());
        try {
            //courseBL.jobserveAllCour((String)listModel.lastElement());
            courseBL = factory.createCourseBL((String)listModel.lastElement());
            CourseVO v = courseBL.jaddCourses(vos);
            if(v==null){
                JOptionPane.showConfirmDialog(this, "添加成功", null, JOptionPane.OK_OPTION);
            }
            else{
                JOptionPane.showConfirmDialog(this, "添加失败，课程号："+v.getCourseID()+"已存在", null, JOptionPane.OK_OPTION);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(AddCoursePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, "网络异常", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_courseButtonActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        // TODO add your handling code here:
        FileDialog fileDialog = new FileDialog(frame,"请选择文件：",FileDialog.LOAD);
        fileDialog.setVisible(true);
        String directory = fileDialog.getDirectory();
        String file  = fileDialog.getFile();
        fileTextField.setText(directory+"/"+file);
    }//GEN-LAST:event_openButtonActionPerformed

    private void fileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileTextFieldActionPerformed
        // TODO add your handling code here:
        commitButtonActionPerformed(evt);
    }//GEN-LAST:event_fileTextFieldActionPerformed

    private void commitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitButtonActionPerformed
        // TODO add your handling code here:
         int i = JOptionPane.showConfirmDialog(this, "确定添加？", null, JOptionPane.OK_CANCEL_OPTION, WIDTH);
        if(i!=JOptionPane.OK_OPTION){
            return ;
        }
        //courseBL = factory.createCourseBL((String)listModel.lastElement());
        try {
            CourseVO v = courseBL.jaddCourses(fileTextField.getText());
            if(v==null){
                JOptionPane.showConfirmDialog(this, "添加成功", null, JOptionPane.OK_OPTION);
                vos = courseBL.jobserveAllCour();
                updateTable();
            }
            else{
                JOptionPane.showConfirmDialog(this, "添加失败，课程号："+v.getCourseID()+"已存在", null, JOptionPane.OK_OPTION);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(AddCoursePanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(this, "网络异常", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_commitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if(v==null){
            return;
        }
        ResultMessage r = courseBL.jdelete(v);
         if(r==ResultMessage.SUCCESS){
        vos.remove(v);
        v = null;
       updateTable();
         JOptionPane.showMessageDialog(this, "删除成功！");
         deleteButton.setEnabled(false);
         modifyButton.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "删除失败！");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        CourInfoFrame c= new CourInfoFrame(courseBL,(String)listModel.lastElement());
        c.setBounds(400,200,543,373);
        c.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        ModifyCourInfoFrame c= new ModifyCourInfoFrame(v,courseBL,(String)listModel.lastElement());
        c.setBounds(400,200,543,373);
        c.setVisible(true);
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
       termListValueChanged(null);
    }//GEN-LAST:event_updateButtonActionPerformed

    public void TableValueChanged(int i){
        if(isEdit){
           deleteButton.setEnabled(true);
             modifyButton.setEnabled(true);
             v = vos.get(i);
        }
        else{
            deleteButton.setEnabled(false);
             modifyButton.setEnabled(false);
        }
        
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addTermButton;
    private javax.swing.JButton commitButton;
    private javax.swing.JButton courseButton;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton openButton;
    private javax.swing.JList termList;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
  private void updateTable(){
        String[][] content = new String[vos.size()][8];
        for (int i = 0; i < vos.size(); i++) {

            //初始化table
            content[i][0] = vos.get(i).getModule();
            content[i][1] = vos.get(i).getProperty();
            content[i][2] = vos.get(i).getType();
            content[i][3] = vos.get(i).getCourseID();
            content[i][4] = vos.get(i).getCourseName();
            content[i][5] = vos.get(i).getCredit();
            content[i][6] = vos.get(i).getHour();
            content[i][7] = vos.get(i).getPeriod();
        }
        String[] head = {"课程模块","课程性质","课程类别","课程号","课程名","学分","周学时","修读年级"};
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        courseTable.setModel(model);

    }
  public void update(){
      vos.clear();
      updateTable();
      termList.clearSelection();
      modifyButton.setEnabled(false);
      isEdit = false;
      deleteButton.setEnabled(isEdit);
      addButton.setEnabled(isEdit);
      fileTextField.setText("");
      openButton.setEnabled(isEdit);
      commitButton.setEnabled(isEdit);
  }
}
