/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

import java.awt.CardLayout;
import java.awt.Color;
import ui.Library.Navigation;
import vo.uservo.UserInfoVO;




/**
 *
 * @author zili chen
 */
public class JWmainFrame extends javax.swing.JFrame {
    
    UserInfoVO userInfoVO;
    /**
     * Creates new form JWmainFrame
     */
    public JWmainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        framePanel = new FramePanel();
        planPanel = new PlanPanel();
        staticsPanel = new StaticsPanel();
        perInfoPanel = new PerInfoPanel(this);
        processMainPanel = new ProcessMainPanel();
        backLabel.setForeground(Color.BLUE);
        homeLabel.setForeground(Color.BLUE);
        exitLabel.setForeground(Color.BLUE);
        isProcess  = processMainPanel.getProcess();
        containPanel.setLayout(cardLayout);//----------------------------卡片面板
        containPanel.add(jwMainPanel,"jwMainP");
        containPanel.add(framePanel,"frameP");
        containPanel.add(planPanel,"planP");
        containPanel.add(staticsPanel,"staticsP");
        containPanel.add(processMainPanel,"processMainP");
        containPanel.add(perInfoPanel,"perInfoP");
        navigation = new Navigation();//-------------------------------导航栏标签
        titelPanel.add(navigation.getArrow(),0,0);
        titelPanel.add(navigation.getNow(),0,0);
        navigation.setNowBounds(201, 7, 84, 19);
    }
    public void setUserInforVO(UserInfoVO userInfoVO){
        this.userInfoVO=userInfoVO;
        perInfoPanel.setUserInfoVO(userInfoVO);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        CSSLabel = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        NJWUPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titelPanel = new javax.swing.JPanel();
        peopleLogo = new javax.swing.JLabel();
        nameLogo = new javax.swing.JLabel();
        arrowLogo = new javax.swing.JLabel();
        currentLogo = new javax.swing.JLabel();
        backLogo = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        homeLogo = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        exitLogo = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        containPanel = new javax.swing.JPanel();
        jwMainPanel = new javax.swing.JPanel();
        frameButton = new javax.swing.JButton();
        staticsButton = new javax.swing.JButton();
        processButton = new javax.swing.JButton();
        personButton = new javax.swing.JButton();
        frameLabel = new javax.swing.JLabel();
        planLabel = new javax.swing.JLabel();
        staticsLabel = new javax.swing.JLabel();
        processLabel = new javax.swing.JLabel();
        personLabel = new javax.swing.JLabel();
        notePanel = new javax.swing.JPanel();
        planButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backPanel.setBackground(new java.awt.Color(0, 0, 0));

        CSSLabel.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        CSSLabel.setForeground(new java.awt.Color(255, 255, 255));
        CSSLabel.setText("CSS");

        ExitButton.setBackground(new java.awt.Color(0, 0, 0));
        ExitButton.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("X");
        ExitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        NJWUPanel.setBackground(new java.awt.Color(233, 233, 237));
        NJWUPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 48)); // NOI18N
        jLabel1.setText("NJWU选课系统");

        javax.swing.GroupLayout NJWUPanelLayout = new javax.swing.GroupLayout(NJWUPanel);
        NJWUPanel.setLayout(NJWUPanelLayout);
        NJWUPanelLayout.setHorizontalGroup(
            NJWUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NJWUPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NJWUPanelLayout.setVerticalGroup(
            NJWUPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NJWUPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        titelPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        peopleLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        peopleLogo.setText("Logo");

        nameLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLogo.setText("name");

        arrowLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        arrowLogo.setText("->");

        currentLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        currentLogo.setText("首页");

        backLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLogo.setText("Logo");

        backLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        backLabel.setText("back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLabelMouseExited(evt);
            }
        });
        backLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backLabelMouseMoved(evt);
            }
        });

        homeLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLogo.setText("Logo");

        homeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        homeLabel.setText("home");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabelMouseExited(evt);
            }
        });
        homeLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                homeLabelMouseMoved(evt);
            }
        });

        exitLogo.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLogo.setText("Logo");

        exitLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        exitLabel.setText("exit");
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
        });
        exitLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout titelPanelLayout = new javax.swing.GroupLayout(titelPanel);
        titelPanel.setLayout(titelPanelLayout);
        titelPanelLayout.setHorizontalGroup(
            titelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peopleLogo)
                .addGap(18, 18, 18)
                .addComponent(nameLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arrowLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backLabel)
                .addGap(18, 18, 18)
                .addComponent(homeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel)
                .addGap(18, 18, 18)
                .addComponent(exitLogo)
                .addGap(5, 5, 5)
                .addComponent(exitLabel)
                .addContainerGap())
        );
        titelPanelLayout.setVerticalGroup(
            titelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleLogo)
                    .addComponent(nameLogo)
                    .addComponent(arrowLogo)
                    .addComponent(currentLogo)
                    .addComponent(backLogo)
                    .addComponent(backLabel)
                    .addComponent(homeLogo)
                    .addComponent(homeLabel)
                    .addComponent(exitLogo)
                    .addComponent(exitLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containPanel.setBackground(new java.awt.Color(0, 0, 0));

        jwMainPanel.setBackground(new java.awt.Color(0, 0, 0));

        frameButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        frameButton.setText("frame");
        frameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameButtonActionPerformed(evt);
            }
        });

        staticsButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        staticsButton.setText("statics");
        staticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staticsButtonActionPerformed(evt);
            }
        });

        processButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        processButton.setText("process");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        personButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        personButton.setText("person");
        personButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personButtonActionPerformed(evt);
            }
        });

        frameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        frameLabel.setForeground(new java.awt.Color(240, 240, 240));
        frameLabel.setText("教学框架");

        planLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        planLabel.setForeground(new java.awt.Color(240, 240, 240));
        planLabel.setText("教学计划");

        staticsLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        staticsLabel.setForeground(new java.awt.Color(240, 240, 240));
        staticsLabel.setText("统计信息");

        processLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        processLabel.setForeground(new java.awt.Color(240, 240, 240));
        processLabel.setText("进程管理");

        personLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        personLabel.setForeground(new java.awt.Color(240, 240, 240));
        personLabel.setText("个人信息");

        notePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        notePanel.setToolTipText("");

        javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
        notePanel.setLayout(notePanelLayout);
        notePanelLayout.setHorizontalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        notePanelLayout.setVerticalGroup(
            notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        planButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        planButton.setText("plan");
        planButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jwMainPanelLayout = new javax.swing.GroupLayout(jwMainPanel);
        jwMainPanel.setLayout(jwMainPanelLayout);
        jwMainPanelLayout.setHorizontalGroup(
            jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jwMainPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jwMainPanelLayout.createSequentialGroup()
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frameButton)
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(frameLabel)))
                        .addGap(52, 52, 52)
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(planButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(planLabel)))
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(staticsLabel)
                                .addGap(71, 71, 71)
                                .addComponent(processLabel))
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(staticsButton)
                                .addGap(53, 53, 53)
                                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jwMainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(personLabel))
                            .addComponent(personButton))))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        jwMainPanelLayout.setVerticalGroup(
            jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jwMainPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staticsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jwMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personLabel)
                    .addComponent(processLabel)
                    .addComponent(frameLabel)
                    .addComponent(planLabel)
                    .addComponent(staticsLabel))
                .addGap(18, 18, 18)
                .addComponent(notePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containPanelLayout = new javax.swing.GroupLayout(containPanel);
        containPanel.setLayout(containPanelLayout);
        containPanelLayout.setHorizontalGroup(
            containPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jwMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        containPanelLayout.setVerticalGroup(
            containPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containPanelLayout.createSequentialGroup()
                .addComponent(jwMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CSSLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(25, 25, 25))
            .addComponent(NJWUPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(containPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CSSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NJWUPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void staticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staticsButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(containPanel,"staticsP");
        navigation.setNowText("统计信息");
        navigation.setVisible(true);
    }//GEN-LAST:event_staticsButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(containPanel,"processMainP");
        navigation.setNowText("进程管理");
        navigation.setVisible(true);
    }//GEN-LAST:event_processButtonActionPerformed

    private void personButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(containPanel, "perInfoP");
        navigation.setNowText("个人信息");
        navigation.setVisible(true);
    }//GEN-LAST:event_personButtonActionPerformed

    private void planButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(containPanel,"planP");
        navigation.setNowText("查看教学计划");
        navigation.setVisible(true);
    }//GEN-LAST:event_planButtonActionPerformed

    private void frameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(containPanel,"frameP");
        navigation.setNowText("教学框架");
        navigation.setVisible(true);
    }//GEN-LAST:event_frameButtonActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        isProcess  = processMainPanel.getProcess();
        if(isProcess) {
            cardLayout.show(containPanel,"processMainP");
            processMainPanel.getMsgPanel().setVisible(false);
            processMainPanel.getTimePanel().setVisible(false);
        }
        else {
            cardLayout.show(containPanel,"jwMainP");
            navigation.setVisible(false);
        }
        isProcess  = false;
    }//GEN-LAST:event_backLabelMouseClicked

    private void backLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseMoved
        // TODO add your handling code here:
        backLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_backLabelMouseMoved

    private void backLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseExited
        // TODO add your handling code here:
        backLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_backLabelMouseExited

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
        cardLayout.show(containPanel,"jwMainP");
        navigation.setVisible(false);
    }//GEN-LAST:event_homeLabelMouseClicked

    private void homeLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseMoved
        // TODO add your handling code here:
        homeLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_homeLabelMouseMoved

    private void homeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseExited
        // TODO add your handling code here:
        homeLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_homeLabelMouseExited

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseMoved
        // TODO add your handling code here:
        exitLabel.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitLabelMouseMoved

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        // TODO add your handling code here:
        exitLabel.setForeground(Color.BLUE);
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabelMouseEntered

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
      //  JOptionPane.showMessageDialog(this, evt);
      //  this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public  void main(String args[], final UserInfoVO userInfoVO) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JWmainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JWmainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JWmainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JWmainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JWmainFrame frame=new JWmainFrame();
                frame.setUserInforVO(userInfoVO);
                frame.setVisible(true);
                System.out.println("@jwmainframe.java"+userInfoVO.toString());
                System.out.println("ususerinfo null:"+(userInfoVO==null));
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CSSLabel;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel NJWUPanel;
    private javax.swing.JLabel arrowLogo;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel backLogo;
    private javax.swing.JPanel backPanel;
    private javax.swing.JPanel containPanel;
    private javax.swing.JLabel currentLogo;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLogo;
    private javax.swing.JButton frameButton;
    private javax.swing.JLabel frameLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JLabel homeLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jwMainPanel;
    private javax.swing.JLabel nameLogo;
    private javax.swing.JPanel notePanel;
    private javax.swing.JLabel peopleLogo;
    private javax.swing.JButton personButton;
    private javax.swing.JLabel personLabel;
    private javax.swing.JButton planButton;
    private javax.swing.JLabel planLabel;
    private javax.swing.JButton processButton;
    private javax.swing.JLabel processLabel;
    private javax.swing.JButton staticsButton;
    private javax.swing.JLabel staticsLabel;
    private javax.swing.JPanel titelPanel;
    // End of variables declaration//GEN-END:variables
    private FramePanel framePanel;
    private PlanPanel planPanel;
    private StaticsPanel staticsPanel;
    private ProcessMainPanel processMainPanel;
    private CardLayout cardLayout;
    private Navigation navigation;
    private boolean isProcess;//for “backLabel”：用来判断是否是process界面
    private PerInfoPanel perInfoPanel;

}
