/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

import ui.YJWTeacher.*;
import businesslogicservice.courseblservice.CourseBLService;
import businesslogicservice.courseblservice.CourseOperationFactory;
import enumeration.ResultMessage;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.Library.MyTitledBorder;
import vo.coursevo.CourseVO;
import vo.planvo.PlanVO;

/**
 *
 * @author zili chen
 */
public class ModifyCourInfoFrame extends javax.swing.JFrame {
String depart;
CourseBLService courseBL;
CourseVO v;
    /**
     * Creates new form PlanInfoFrame
     */
    public ModifyCourInfoFrame(CourseVO v,CourseBLService courseBL,String term) {
        
        this.courseBL = courseBL;
        this.term =term;
       this.v = v;
        initComponents();
        this.setLocationRelativeTo(null);
        backPanel.setBorder(new MyTitledBorder("课程信息").getTitledBorder());
        
        idTextField.setText(v.getCourseID());
        nameTextField.setText(v.getCourseName());
        moduleComboBox.setSelectedItem(v.getModule());
        propertyComboBox.setSelectedItem(v.getProperty());
        isOpenComboBox.setSelectedItem(v.getIsOpen());
        typeComboBox.setSelectedItem(v.getType());
        periodComboBox.setSelectedItem(v.getPeriod());
        creditComboBox.setSelectedItem(v.getCredit());
        hourComboBox.setSelectedItem(v.getHour());
        teaNameTextField.setText(v.getTeaName());
        teaIDTextField.setText(v.getTeaID());
        timeTextField.setText(v.getTime());
        insOpenComboBox.setSelectedItem(v.getInstitute());
        
        peopleNumTextField.setText(v.getPeopleNum());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        hourLabel = new javax.swing.JLabel();
        sureButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        propertyLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        creditLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        propertyComboBox = new javax.swing.JComboBox();
        typeComboBox = new javax.swing.JComboBox();
        hourComboBox = new javax.swing.JComboBox();
        creditComboBox = new javax.swing.JComboBox();
        insLabel = new javax.swing.JLabel();
        insComboBox = new javax.swing.JComboBox();
        termLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        isOpenComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        periodComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        teaIDTextField = new javax.swing.JTextField();
        teaNameTextField = new javax.swing.JTextField();
        timeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        moduleComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        insOpenComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        peopleNumTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        backPanel.setBackground(new java.awt.Color(0, 0, 0));
        backPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 102), 2, true), "课程信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 1, 14), new java.awt.Color(255, 0, 102))); // NOI18N

        idTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        nameTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        hourLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        hourLabel.setForeground(new java.awt.Color(204, 204, 204));
        hourLabel.setText("周学时");

        sureButton.setBackground(new java.awt.Color(0, 0, 0));
        sureButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sureButton.setText("确认");
        sureButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        sureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sureButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cancelButton.setText("取消");
        cancelButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        propertyLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        propertyLabel.setForeground(new java.awt.Color(204, 204, 204));
        propertyLabel.setText("课程性质");

        nameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel.setText("课程名");

        idLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(204, 204, 204));
        idLabel.setText("课程编号");

        creditLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        creditLabel.setForeground(new java.awt.Color(204, 204, 204));
        creditLabel.setText("学分");

        typeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(204, 204, 204));
        typeLabel.setText("课程类别");

        propertyComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        propertyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "必修", "选修" }));
        propertyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyComboBoxActionPerformed(evt);
            }
        });

        typeComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "通识教育", "思想政治理论", "军事", "分层次通修", "学科平台", "专业核心", "专业选修", "跨专业选修", "公共选修", "第二课堂", "毕业论文/设计" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        hourComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        hourComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        hourComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourComboBoxActionPerformed(evt);
            }
        });

        creditComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        creditComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        creditComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditComboBoxActionPerformed(evt);
            }
        });

        insLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insLabel.setForeground(new java.awt.Color(204, 204, 204));
        insLabel.setText("修读院系");

        insComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "软件学院", "商学院", "医学院" }));
        insComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insComboBoxActionPerformed(evt);
            }
        });

        termLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        termLabel.setForeground(new java.awt.Color(204, 204, 204));
        termLabel.setText("上课时间");

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("是否开放");

        isOpenComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        isOpenComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "是", "否" }));

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("修读年纪");

        periodComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        periodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "大一上", "大一下", "大二上", "大二下", "大三上", "大三下", "大四上", "大四下", "All" }));

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("任课老师ID");

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("任课老师姓名");

        teaIDTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        teaIDTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        teaIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaIDTextFieldActionPerformed(evt);
            }
        });

        teaNameTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        teaNameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        teaNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaNameTextFieldActionPerformed(evt);
            }
        });

        timeTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        timeTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        timeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("课程模块");

        moduleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "通识", "通修" }));

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("开课院系");

        insOpenComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "软件学院", "商学院", "医学院", "政府管理学院", "法学院" }));

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("人数（0表示无限制）");

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(sureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(isOpenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(propertyLabel)
                                    .addComponent(creditLabel)
                                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(backPanelLayout.createSequentialGroup()
                                            .addComponent(insLabel)
                                            .addGap(38, 38, 38)
                                            .addComponent(insComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(backPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(38, 38, 38)
                                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(propertyComboBox, 0, 151, Short.MAX_VALUE)
                                                .addComponent(moduleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(backPanelLayout.createSequentialGroup()
                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(teaIDTextField)
                                            .addComponent(insOpenComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backPanelLayout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(periodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addComponent(hourLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeLabel)
                                    .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(termLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeTextField)
                                    .addComponent(teaNameTextField)))))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peopleNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(moduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propertyLabel)
                    .addComponent(typeLabel)
                    .addComponent(propertyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditLabel)
                    .addComponent(creditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourLabel)
                    .addComponent(hourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(isOpenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(periodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(teaIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teaNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(insOpenComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(peopleNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insLabel)
                    .addComponent(termLabel)
                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sureButtonActionPerformed
        // TODO add your handling code here:
        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        if(idTextField.getText().equals("")||nameTextField.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "课程号和课程名不能为空", null, JOptionPane.OK_OPTION);
            return ;
        }
        int i = JOptionPane.showConfirmDialog(this, "确定添加？", null, JOptionPane.OK_CANCEL_OPTION, WIDTH);
        if(i!=JOptionPane.OK_OPTION){
            return ;
        }
        v.setCourseID(idTextField.getText());
        v.setCourseName(nameTextField.getText());
        v.setModule((String)moduleComboBox.getSelectedItem());
         v.setProperty((String)propertyComboBox.getSelectedItem());
         v.setIsOpen((String)isOpenComboBox.getSelectedItem());
          v.setType((String)typeComboBox.getSelectedItem());
          v.setPeriod((String)periodComboBox.getSelectedItem());
           v.setCredit((String)creditComboBox.getSelectedItem());
                   v.setHour((String)hourComboBox.getSelectedItem());
           v.setTeaName( teaNameTextField.getText());
           v.setTeaID(teaIDTextField.getText());
           v.setTime(timeTextField.getText());
            v.setInstitute((String)insOpenComboBox.getSelectedItem());
               v.setLearnIns( "All");
               v.setPeopleNum(peopleNumTextField.getText());
        //pvo = new PlanVO(institute,term,module,property,type,courseID,courseName+"",credit+"",hour+"","");
        ResultMessage r;
        if((r=courseBL.jupdateCourse(v))==ResultMessage.SUCCESS){
             JOptionPane.showConfirmDialog(this, "修改成功！", null, JOptionPane.OK_OPTION);
              dispose();
        }
       
        else{
             JOptionPane.showConfirmDialog(this, "修改失败！", null, JOptionPane.OK_OPTION);
        }
       
    }//GEN-LAST:event_sureButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
        courseID = idTextField.getText();
        nameTextField.requestFocus();
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
        courseName =  nameTextField.getText();
        teaIDTextField.requestFocus();
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void propertyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyComboBoxActionPerformed
        // TODO add your handling code here:
      //  property = propertyComboBox.getToolTipText();
    }//GEN-LAST:event_propertyComboBoxActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
      //  type = typeComboBox.getToolTipText();
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void creditComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditComboBoxActionPerformed
        // TODO add your handling code here:
      //  credit = Integer.parseInt(creditComboBox.getToolTipText());
    }//GEN-LAST:event_creditComboBoxActionPerformed

    private void hourComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourComboBoxActionPerformed
        // TODO add your handling code here:
        //hour = Integer.parseInt(hourComboBox.getToolTipText());
    }//GEN-LAST:event_hourComboBoxActionPerformed

    private void insComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insComboBoxActionPerformed
        // TODO add your handling code here:
       // institute = insComboBox.getToolTipText();
    }//GEN-LAST:event_insComboBoxActionPerformed

    private void teaIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaIDTextFieldActionPerformed
        // TODO add your handling code here:
        teaNameTextField.requestFocus();
    }//GEN-LAST:event_teaIDTextFieldActionPerformed

    private void teaNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaNameTextFieldActionPerformed
        // TODO add your handling code here:
        timeTextField.requestFocus();
    }//GEN-LAST:event_teaNameTextFieldActionPerformed

    private void timeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFieldActionPerformed
        // TODO add your handling code here:
        sureButtonActionPerformed(evt);
    }//GEN-LAST:event_timeTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyCourInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyCourInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyCourInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyCourInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyCourInfoFrame(null,null,"").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox creditComboBox;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JComboBox hourComboBox;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JComboBox insComboBox;
    private javax.swing.JLabel insLabel;
    private javax.swing.JComboBox insOpenComboBox;
    private javax.swing.JComboBox isOpenComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox moduleComboBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField peopleNumTextField;
    private javax.swing.JComboBox periodComboBox;
    private javax.swing.JComboBox propertyComboBox;
    private javax.swing.JLabel propertyLabel;
    private javax.swing.JButton sureButton;
    private javax.swing.JTextField teaIDTextField;
    private javax.swing.JTextField teaNameTextField;
    private javax.swing.JLabel termLabel;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
    
    /*逻辑处理*/
    private String institute;//院系
    private String term;//学期：2012-1,2012-2
    private String module;//课程模块：通识通修
    private String property;//课程性质：指选、必修、选修
    private String type;//课程类别：通识教育
    private String courseID;//课程号
    private String courseName;//课程名
    private int credit;//学分
    private int hour;//周学时
    private PlanVO pvo;
    
    public void setModule(String module) {
        this.module = module;
    }
  
}
