/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import ui.Library.ImageIconFactory;
import ui.Library.LogoButton;
import ui.Library.Navigation;
import ui.Library.TextLabel;

/**
 *
 * @author zili Chen
 */
public class ProcessPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessPanel
     */
    public ProcessPanel() {
        initComponents();
        /*GUI-主panel*/
        setOpaque(false);
        navPanel.setOpaque(false);
        /*GUI-导航*/
        image = new ImageIconFactory();
        navigation = new Navigation(navPanel,JWMain.card,JWMain.contain,"mainP");
        /*GUI-进程管理*/
        timeButton = new LogoButton(80,100).getJModifyrButton();
        timeLabel = new TextLabel(image.getPTimeIcon(),80,170).getLabel();
        noticeButton = new LogoButton(200,100).getJTwoDocButton();
        noticeLabel = new TextLabel(image.getPNoticeIcon(),200,170).getLabel();
        timeButton.addMouseListener(new TimeListener());//时间安排按钮
        add(timeButton);
        add(timeLabel);
        noticeButton.addMouseListener(new NoticeListener());//通知公告按钮
        add(noticeButton);
        add(noticeLabel);
    }
    
    /*事件-时间安排*/
    class TimeListener implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            JWMain.card.show(JWMain.contain,"timeP");
        }

        @Override
        public void mousePressed(MouseEvent e) {
            timeButton.setContentAreaFilled(true);
            timeButton.setOpaque(false);
            timeButton.setBackground(Color.black);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            timeButton.setContentAreaFilled(false);
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }
        
    }
    
    /*事件-通知通告*/
    class NoticeListener implements MouseListener {

        @Override
        public void mouseClicked(MouseEvent e) {
            JWMain.card.show(JWMain.contain,"noticeP");
        }

        @Override
        public void mousePressed(MouseEvent e) {
            noticeButton.setContentAreaFilled(true);
            noticeButton.setOpaque(false);
            noticeButton.setBackground(Color.black);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            noticeButton.setContentAreaFilled(false);
        }

        @Override
        public void mouseEntered(MouseEvent e) {
        }

        @Override
        public void mouseExited(MouseEvent e) {
        }
        
    }

    public void update() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPanel = new javax.swing.JPanel();

        navPanel.setBackground(new java.awt.Color(51, 255, 102));

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 365, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel navPanel;
    // End of variables declaration//GEN-END:variables
    /*GUI-导航*/
    private ImageIconFactory image;
    private Navigation navigation;
    /*GUI-进程管理*/
    private JButton timeButton;
    private JButton noticeButton;
    private JLabel timeLabel;
    private JLabel noticeLabel;
}
