/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

import businesslogic.processmngbl.noticebl.Notice;
import businesslogic.processmngbl.noticebl.NoticeFactory;
import businesslogic.processmngbl.noticebl.NoticeList;
import businesslogicservice.processmngblservice.notice.NoticeBLService;
import businesslogicservice.processmngblservice.notice.ROLE;
import java.util.Date;
import java.util.Iterator;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import vo.processmngvo.NoticeVO;

/**
 *
 * @author zili chen
 */
public class SendMsgPanel extends javax.swing.JPanel {

    int currentNoticeNum = 0;
    NoticeBLService nbls;
    NoticeFactory nf = new NoticeFactory();
    NoticeList noticeList;
    private ButtonGroup buttonGroup = new ButtonGroup();

    /**
     * Creates new form SendMsgPanel
     */
    public SendMsgPanel() {
        initComponents();
        showMSGPanel(false);
        nbls = nf.createNoticeBL();
        noticeList = nbls.getNoticeList();
        System.out.println();
        refreshNoticelistUI();
        initButtonGroup();
    }

    public void initButtonGroup() {
        buttonGroup.add(allChoose);
        buttonGroup.add(teacherChoose);
        buttonGroup.add(studentChoose);
        buttonGroup.add(insJWchoose);
    }

    public void showMSGPanel(boolean b) {
        msgPanel.setVisible(b);
    }

    public void refreshNoticePanel(int indexOfNoticeList) {
        Notice notice = noticeList.getX(indexOfNoticeList+1);
        titleTextField.setText(notice.getName());
        msgTextArea.setText(notice.getContent());
        refreshRadioButtons(notice.getRole());
    }
    public void setNoticePanelEditable(boolean  editable){
        titleTextField.setEditable(editable);
        msgTextArea.setEditable(editable);
    }
    public void refreshRadioButtons(ROLE role){
        teacherChoose.setSelected(false);
        studentChoose.setSelected(false);
        allChoose.setSelected(false);
        insJWchoose.setSelected(false);
       JRadioButton button=getSelectedButton(role);
       button.setSelected(true);
    }

    public JRadioButton getSelectedButton(ROLE role) {
        switch (role) {
            case TEACHER:
                return teacherChoose;
            case STUDENT:
                return studentChoose;
            case INSJW:
               return insJWchoose;
            case BEGINNER:
                return studentChoose;
            case ALL:
                return allChoose;
            default:
                throw new AssertionError(role.name());
        }
    }

    public void refreshNoticelistUI() {
        DefaultListModel listModel = new DefaultListModel();
        if (!noticeList.isEmpty()) {
            Iterator<Notice> itr = noticeList.getIterator();
            while (itr.hasNext()) {
                listModel.addElement(itr.next().getName());
                this.currentNoticeNum++;
            }
        } else {
            listModel.clear();
        }
        sendedList.setModel(listModel);
    }

    public void clearMSGPanel() {
        //  msgTextArea.removeAll();
        //teacherChoose.removeAll();
        //studentChoose.removeAll();
        //insJWchoose.removeAll();
        titleTextField.setText("");
        msgTextArea.setText("");
        teacherChoose.setSelected(false);
        studentChoose.setSelected(false);
        insJWchoose.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendedPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sendedList = new javax.swing.JList();
        addmsgButton = new javax.swing.JButton();
        msgPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        receiverLabel = new javax.swing.JLabel();
        sureButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        insJWchoose = new javax.swing.JRadioButton();
        teacherChoose = new javax.swing.JRadioButton();
        studentChoose = new javax.swing.JRadioButton();
        allChoose = new javax.swing.JRadioButton();
        msgLabel1 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        sendedPanel.setBackground(new java.awt.Color(0, 0, 0));
        sendedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "已发送通知", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        sendedList.setBackground(new java.awt.Color(240, 240, 240));
        sendedList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sendedList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        sendedList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendedListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sendedList);

        addmsgButton.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        addmsgButton.setText("+");
        addmsgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmsgButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sendedPanelLayout = new javax.swing.GroupLayout(sendedPanel);
        sendedPanel.setLayout(sendedPanelLayout);
        sendedPanelLayout.setHorizontalGroup(
            sendedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(sendedPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(addmsgButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        sendedPanelLayout.setVerticalGroup(
            sendedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addmsgButton)
                .addGap(12, 12, 12))
        );

        msgPanel.setBackground(new java.awt.Color(0, 0, 0));
        msgPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        titleLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 204, 204));
        titleLabel.setText("主题");

        msgTextArea.setBackground(new java.awt.Color(240, 240, 240));
        msgTextArea.setColumns(20);
        msgTextArea.setRows(5);
        msgTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane2.setViewportView(msgTextArea);

        receiverLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        receiverLabel.setForeground(new java.awt.Color(204, 204, 204));
        receiverLabel.setText("通知对象");

        sureButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sureButton.setText("确认");
        sureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sureButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cancelButton.setText("取消");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        insJWchoose.setBackground(new java.awt.Color(0, 0, 0));
        insJWchoose.setForeground(new java.awt.Color(255, 255, 255));
        insJWchoose.setText("院系教务员\n");
        insJWchoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insJWchooseActionPerformed(evt);
            }
        });

        teacherChoose.setBackground(new java.awt.Color(0, 0, 0));
        teacherChoose.setForeground(new java.awt.Color(255, 255, 255));
        teacherChoose.setText("教师");

        studentChoose.setBackground(new java.awt.Color(0, 0, 0));
        studentChoose.setForeground(new java.awt.Color(255, 255, 255));
        studentChoose.setText("学生");

        allChoose.setBackground(new java.awt.Color(0, 0, 0));
        allChoose.setForeground(new java.awt.Color(255, 255, 255));
        allChoose.setText("所有用户");

        msgLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        msgLabel1.setForeground(new java.awt.Color(204, 204, 204));
        msgLabel1.setText("内容");

        javax.swing.GroupLayout msgPanelLayout = new javax.swing.GroupLayout(msgPanel);
        msgPanel.setLayout(msgPanelLayout);
        msgPanelLayout.setHorizontalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(msgPanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(sureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(msgPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(msgPanelLayout.createSequentialGroup()
                                .addComponent(receiverLabel)
                                .addGap(70, 70, 70)
                                .addComponent(insJWchoose)
                                .addGap(53, 53, 53)
                                .addComponent(teacherChoose)
                                .addGap(27, 27, 27)
                                .addComponent(studentChoose)
                                .addGap(18, 18, 18)
                                .addComponent(allChoose))
                            .addGroup(msgPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(msgPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(titleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleTextField)))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(msgPanelLayout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(msgLabel1)
                    .addContainerGap(564, Short.MAX_VALUE)))
        );
        msgPanelLayout.setVerticalGroup(
            msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(msgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insJWchoose)
                    .addComponent(studentChoose)
                    .addComponent(allChoose)
                    .addComponent(teacherChoose)
                    .addComponent(receiverLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sureButton)
                    .addComponent(cancelButton)))
            .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(msgPanelLayout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(msgLabel1)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(sendedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addmsgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmsgButtonActionPerformed
        // TODO add your handling code here:
        showMSGPanel(true);
        setNoticePanelEditable(true);
        clearMSGPanel();
    }//GEN-LAST:event_addmsgButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        showMSGPanel(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void sureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sureButtonActionPerformed
        // TODO add your handling code here:
        String name = titleTextField.getText();
        String content = msgTextArea.getText();
        System.out.println("@send msg panel :content" + content);
        boolean chooseInsJW = insJWchoose.isSelected();
        boolean chooseTeacher = teacherChoose.isSelected();
        boolean chooseStudent = studentChoose.isSelected();
        boolean chooseAll = allChoose.isSelected();
        NoticeVO noticeVO = null;
        Date date = new Date();
        if (chooseAll) {
            noticeVO = new NoticeVO(name, content, date);
        } else {
            noticeVO = new NoticeVO(name, content, date, chooseInsJW, chooseTeacher, chooseStudent);
        }
        nbls.send(noticeVO);
        refreshNoticelistUI();
    }//GEN-LAST:event_sureButtonActionPerformed

    private void insJWchooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insJWchooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insJWchooseActionPerformed

    private void sendedListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendedListMouseClicked
        // TODO add your handling code here:
        refreshNoticePanel(sendedList.getSelectedIndex());
        setNoticePanelEditable(false);
        showMSGPanel(true);
    }//GEN-LAST:event_sendedListMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmsgButton;
    private javax.swing.JRadioButton allChoose;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton insJWchoose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel msgLabel1;
    private javax.swing.JPanel msgPanel;
    private javax.swing.JTextArea msgTextArea;
    private javax.swing.JLabel receiverLabel;
    private javax.swing.JList sendedList;
    private javax.swing.JPanel sendedPanel;
    private javax.swing.JRadioButton studentChoose;
    private javax.swing.JButton sureButton;
    private javax.swing.JRadioButton teacherChoose;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
