/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.JWTeacher;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import ui.Library.ComboBox;
import ui.Library.LogoButton;
import ui.Library.ScrollPane;
import ui.Library.Table;
import ui.Library.TextField;
import ui.Library.TextLabel;

/**
 *
 * @author zili Chen
 */
public class StaStuPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaStuPanel
     */
    public StaStuPanel() {
        initComponents();
        /*GUI*/
        int xs1 = 10;
        int xs2 = 130;
        int ys1 = 10;
        int ys2 = ys1+50;
        int ys3 = ys2+50;
        totalLabel = new TextLabel("院系总人数",xs1,ys1,100,30).getLabel();
        notpassLabel = new TextLabel("院系无挂科人数",xs1,ys2,100,30).getLabel();
        percentLabel = new TextLabel("无挂科率",xs1,ys3,100,30).getLabel();
        totalTextField = new TextField(xs2,ys1,120,30).getTextField();
        notpassTextField = new TextField(xs2,ys2,120,30).getTextField();
        percentTextField = new TextField(xs2,ys3,120,30).getTextField();
        stuidLabel = new TextLabel("学生学号",300,ys1+10,60,30).getLabel();
        stuidTextField = new TextField(380,ys1+10,150,30).getTextField();
        searchButton = new LogoButton(540,ys1-8).getLSearchButton();
        ArrayList<String> content1 = new ArrayList<String>();
        content1.add("All");
        ArrayList<String> content2 = new ArrayList<String>();
        content2.add("All");
        comboBox1 = new ComboBox(content1,625,ys1+10,80,30).getComboBox();
        comboBox2 = new ComboBox(content2,715,ys1+10,80,30).getComboBox();
        stuScroll = new ScrollPane(300,ys1+53,500,250).getScrollPane();
        ArrayList<String> content3 = new ArrayList<String>();
        content3.add("0001;软件工程;4;软件学院;学科专业");
        ArrayList<String> head = new ArrayList<String>();
        head.add("课程号");head.add("课程名");head.add("学分");head.add("开课院系");head.add("性质");
        String s = ";";
        stuTable = new Table(content3,head,s).getTable();
        stuScroll.setViewportView(stuTable);
        creditButton = new LogoButton(300,315).getLCreditButton();
        creditLabel = new TextLabel("总学分",360,325,80,30).getLabel();
        add(totalLabel);add(notpassLabel);add(percentLabel);
        add(totalTextField);add(notpassTextField);add(percentTextField);
        add(stuidLabel);add(stuidTextField);
        add(searchButton);
        add(comboBox1);add(comboBox2);
        add(stuScroll);
        add(creditButton);add(creditLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /*GUI*/
    private JLabel totalLabel;
    private JLabel notpassLabel;
    private JLabel percentLabel;
    private JLabel stuidLabel;
    private JLabel creditLabel;
    private JTextField totalTextField;
    private JTextField notpassTextField;
    private JTextField percentTextField;
    private JTextField stuidTextField;
    private JButton searchButton;
    private JButton creditButton;
    private JComboBox comboBox1;
    private JComboBox comboBox2;
    private JScrollPane stuScroll;
    private JTable stuTable;
}
