/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.YJWTeacher;


import businesslogicservice.courseblservice.CourseBLService;
import businesslogicservice.courseblservice.CourseOperationFactory;
import enumeration.ResultMessage;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import  ui.Library.CheckListCellRenderer;
import  ui.Library.CheckValue;
import  ui.Library.FullComboBox;
import  ui.Library.MyComboBox;
import  ui.Library.MyTitledBorder;
import vo.coursevo.CourseVO;
import vo.uservo.UserInfoVO;


/**
 *
 * @author zili chen
 */
public class CoursePanel extends javax.swing.JPanel {
UserInfoVO userInfo;
String ip;
int port;
CourseBLService courseBL;
CourseOperationFactory factory = new CourseOperationFactory();
ArrayList<CourseVO> vos;
CourseVO v;
DefaultListModel listModel = new DefaultListModel();
boolean isEdit =false;
    /**
     * Creates new form CoursePanel
     */
    public CoursePanel(UserInfoVO v,String ip,int port) {
         this.userInfo = v;
        this.ip = ip;
        this.port = port;
       
        initComponents();
        
        
        coursePanel.setBorder(new MyTitledBorder("可开设课程列表").getTitledBorder());
        courseInfoPanel.setBorder(new MyTitledBorder("课程信息").getTitledBorder());
        /*多选下拉框——修读院系*/
       /* insFull = new FullComboBox();
        learnInsComboBox = insFull.getComboBox();
        insFull.add("法学院");
        insFull.add("软件学院");
        insFull.add("商学院");
        insFull.add("医学院");
        insFull.add("政府管理学院");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 40;
        //insComboBox.setBounds(0, 0, 72, 25);
        courseInfoPanel.add(learnInsComboBox, gridBagConstraints);
        learnInsComboBox.setVisible(true);*/
        /*逻辑处理*/
        
        courseBL = factory.createCourseBL();
        String[] s=courseBL.getAllTerms();
        for(String str:s){
            listModel.addElement(str);
        }
        termList.setModel(listModel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        createButton5 = new javax.swing.JButton();
        creditComboBox2 = new javax.swing.JComboBox();
        coursePanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        courseInfoPanel = new javax.swing.JPanel();
        idLabel1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        creditLabel = new javax.swing.JLabel();
        creditComboBox = new javax.swing.JComboBox();
        hourLabel = new javax.swing.JLabel();
        hourComboBox = new javax.swing.JComboBox();
        teacherLabel = new javax.swing.JLabel();
        teaNameTextField = new javax.swing.JTextField();
        timeLabel = new javax.swing.JLabel();
        leanInsTextField = new javax.swing.JTextField();
        insLabel = new javax.swing.JLabel();
        learnInsLabel = new javax.swing.JLabel();
        teaIDTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isOpenComboBox = new javax.swing.JComboBox();
        propertyComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        modualComboBox = new javax.swing.JComboBox();
        periodComboBox = new javax.swing.JComboBox();
        timeTextField = new javax.swing.JTextField();
        insTextField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        sureButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addStuButton = new javax.swing.JButton();
        cancelAddButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        termList = new javax.swing.JList();

        createButton5.setBackground(new java.awt.Color(0, 0, 0));
        createButton5.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        createButton5.setText("开设课程");
        createButton5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        createButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButton5ActionPerformed(evt);
            }
        });

        creditComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(0, 0, 0));

        coursePanel.setBackground(new java.awt.Color(0, 0, 0));
        coursePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "可开设课程列表", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        idLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(240, 240, 240));
        idLabel.setText("课程号");

        nameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(240, 240, 240));
        nameLabel.setText("课程名");

        courseTable.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "课程号", "课程名", "学分"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(courseTable);
        courseTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e) {
                int s[] = courseTable.getSelectedRows();
                if(s.length<1)
                return;
                if(s[0]>=0){
                    TableValueChanged(s[0]);

                }
            }
        });

        idTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        nameTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coursePanelLayout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(nameLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        courseInfoPanel.setBackground(new java.awt.Color(0, 0, 0));
        courseInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "课程信息", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N
        java.awt.GridBagLayout courseInfoPanelLayout = new java.awt.GridBagLayout();
        courseInfoPanelLayout.columnWidths = new int[] {0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0};
        courseInfoPanelLayout.rowHeights = new int[] {0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0, 3, 0};
        courseInfoPanel.setLayout(courseInfoPanelLayout);

        idLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel1.setForeground(new java.awt.Color(240, 240, 240));
        idLabel1.setText("模块");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(idLabel1, gridBagConstraints);

        nameLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(240, 240, 240));
        nameLabel1.setText("性质");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(nameLabel1, gridBagConstraints);

        typeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(240, 240, 240));
        typeLabel.setText("类型");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(typeLabel, gridBagConstraints);

        typeComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "思想政治", "学科平台", "专业选修", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(typeComboBox, gridBagConstraints);

        creditLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        creditLabel.setForeground(new java.awt.Color(240, 240, 240));
        creditLabel.setText("学分");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(creditLabel, gridBagConstraints);

        creditComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        creditComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 131;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(creditComboBox, gridBagConstraints);

        hourLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        hourLabel.setForeground(new java.awt.Color(240, 240, 240));
        hourLabel.setText("周学时");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(hourLabel, gridBagConstraints);

        hourComboBox.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        hourComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(hourComboBox, gridBagConstraints);

        teacherLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        teacherLabel.setForeground(new java.awt.Color(240, 240, 240));
        teacherLabel.setText("授课老师");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(teacherLabel, gridBagConstraints);

        teaNameTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        teaNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaNameTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(teaNameTextField, gridBagConstraints);

        timeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(240, 240, 240));
        timeLabel.setText("授课时间");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(timeLabel, gridBagConstraints);

        leanInsTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        leanInsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leanInsTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.ipadx = 163;
        courseInfoPanel.add(leanInsTextField, gridBagConstraints);

        insLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insLabel.setForeground(new java.awt.Color(240, 240, 240));
        insLabel.setText("开课院系");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(insLabel, gridBagConstraints);

        learnInsLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        learnInsLabel.setForeground(new java.awt.Color(240, 240, 240));
        learnInsLabel.setText("修读院系");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(learnInsLabel, gridBagConstraints);

        teaIDTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(teaIDTextField, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("老师ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        courseInfoPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("是否开放");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        courseInfoPanel.add(jLabel2, gridBagConstraints);

        isOpenComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "否", "是" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        courseInfoPanel.add(isOpenComboBox, gridBagConstraints);

        propertyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "必修", "选修" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 13;
        courseInfoPanel.add(propertyComboBox, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("修读年纪");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        courseInfoPanel.add(jLabel3, gridBagConstraints);

        modualComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "通识", "通修", "学科专业", "毕业论文/设计" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 6;
        courseInfoPanel.add(modualComboBox, gridBagConstraints);

        periodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "大一上", "大一下", "大二上", "大二下", "大三上", "大三下", "大四上", "大四下", "All" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 10;
        courseInfoPanel.add(periodComboBox, gridBagConstraints);

        timeTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.ipadx = 163;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        courseInfoPanel.add(timeTextField, gridBagConstraints);

        insTextField.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.ipadx = 163;
        courseInfoPanel.add(insTextField, gridBagConstraints);

        deleteButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(204, 204, 204));
        deleteButton.setText("删除课程");
        deleteButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        modifyButton.setBackground(new java.awt.Color(0, 0, 0));
        modifyButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        modifyButton.setForeground(new java.awt.Color(204, 204, 204));
        modifyButton.setText("编辑课程");
        modifyButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        modifyButton.setEnabled(false);
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        sureButton.setBackground(new java.awt.Color(0, 0, 0));
        sureButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sureButton.setForeground(new java.awt.Color(204, 204, 204));
        sureButton.setText("确认");
        sureButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        sureButton.setEnabled(false);
        sureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sureButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(204, 204, 204));
        cancelButton.setText("取消");
        cancelButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addStuButton.setBackground(new java.awt.Color(0, 0, 0));
        addStuButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        addStuButton.setForeground(new java.awt.Color(204, 204, 204));
        addStuButton.setText("添加学生名单");
        addStuButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        addStuButton.setEnabled(false);
        addStuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStuButtonActionPerformed(evt);
            }
        });

        cancelAddButton.setBackground(new java.awt.Color(0, 0, 0));
        cancelAddButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cancelAddButton.setForeground(new java.awt.Color(204, 204, 204));
        cancelAddButton.setText("撤销名单添加");
        cancelAddButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true)));
        cancelAddButton.setEnabled(false);
        cancelAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddButtonActionPerformed(evt);
            }
        });

        termList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                termListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(termList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cancelAddButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(addStuButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(215, 215, 215))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addStuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if(v==null){
            return ;
        }
        if(v.getModule().equals("通修")){
            JOptionPane.showMessageDialog(this, "无权删除！");
            return;
        }
        if(courseBL.delete(v.getCourseID())==ResultMessage.SUCCESS){
        vos.remove(v);
        v = null;
        String[][] content = new String[vos.size()][3];
        for (int i = 0; i < vos.size(); i++) {

            //初始化table

            content[i][0] = vos.get(i).getCourseID();
            content[i][1] = vos.get(i).getCourseName();
            content[i][2] = vos.get(i).getCredit();
        }
        String[] head = {"课程号","课程名","学分"};
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        courseTable.setModel(model);
         JOptionPane.showMessageDialog(this, "删除成功！");
         deleteButton.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "删除失败！");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        sureButton.setEnabled(true);
        if(!((String)modualComboBox.getSelectedItem()).equals("通修")){
             modualComboBox.setEnabled(true);
        propertyComboBox.setEnabled(true);
        periodComboBox.setEnabled(true);
        isOpenComboBox.setEnabled(true);
        typeComboBox.setEnabled(true);
        creditComboBox.setEnabled(true);
        hourComboBox.setEnabled(true);
        leanInsTextField.setEnabled(true);
       // insTextField.setEditable(true);
        //materialTextField.setText(v.getMaterial());
        //insTextField.setEditable(false);
        }
        timeTextField.setEnabled(true);
        teaIDTextField.setEditable(true);
        teaNameTextField.setEditable(true);
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void sureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sureButtonActionPerformed
        // TODO add your handling code here:
        v.setModule((String)modualComboBox.getSelectedItem());
         v.setProperty((String)propertyComboBox.getSelectedItem());
         v.setPeriod((String)periodComboBox.getSelectedItem());
         v.setIsOpen((String)isOpenComboBox.getSelectedItem());
          v.setType((String)typeComboBox.getSelectedItem());
           v.setCredit((String)creditComboBox.getSelectedItem());
          v.setHour((String)hourComboBox.getSelectedItem());
          v.setTeaID((String)teaIDTextField.getText());
           v.setTeaName((String)teaNameTextField.getText());
           ResultMessage r;
           if(v.getModule().equals("通修")){
               r = courseBL.jupdateCourse(v);
           }
           else{
               r =courseBL.modifyCourse(v);
           }
        if(r==ResultMessage.SUCCESS){
            JOptionPane.showMessageDialog(this, "修改成功！");
        } else {
            JOptionPane.showMessageDialog(this, "修改失败！");
        }
        
    }//GEN-LAST:event_sureButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
       
        if(v==null){
            
            return ;
        }
        modualComboBox.setSelectedItem(v.getModule());
        propertyComboBox.setSelectedItem(v.getProperty());
        periodComboBox.setSelectedItem(v.getPeriod());
        isOpenComboBox.setSelectedIndex(Integer.parseInt(v.getIsOpen()));
        typeComboBox.setSelectedItem(v.getType());
        creditComboBox.setSelectedItem(v.getCredit());
        hourComboBox.setSelectedItem(v.getHour());
        teaIDTextField.setText(v.getTeaID());
        teaNameTextField.setText(v.getTeaName());
        leanInsTextField.setText(v.getInstitute());
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addStuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStuButtonActionPerformed
        // TODO add your handling code here:
                if(v==null){
            return ;
        }
    }//GEN-LAST:event_addStuButtonActionPerformed

    private void createButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createButton5ActionPerformed

    private void cancelAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddButtonActionPerformed
        // TODO add your handling code here:
                if(v==null){
            return ;
        }
    }//GEN-LAST:event_cancelAddButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
         nameTextField.setText("");
         vos = courseBL.findCourseID(idTextField.getText());
        String[][] content = new String[vos.size()][3];
        for (int i = 0; i < vos.size(); i++) {

            //初始化table

            content[i][0] = vos.get(i).getCourseID();
            content[i][1] = vos.get(i).getCourseName();
            content[i][2] = vos.get(i).getCredit();
        }
        String[] head = {"课程号","课程名","学分"};
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        courseTable.setModel(model);
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
         idTextField.setText("");
         vos = courseBL.findCourseName(nameTextField.getText());
        String[][] content = new String[vos.size()][3];
        for (int i = 0; i < vos.size(); i++) {

            //初始化table

            content[i][0] = vos.get(i).getCourseID();
            content[i][1] = vos.get(i).getCourseName();
            content[i][2] = vos.get(i).getCredit();
        }
        String[] head = {"课程号","课程名","学分"};
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        courseTable.setModel(model);
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void teaNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaNameTextFieldActionPerformed

    private void leanInsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leanInsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leanInsTextFieldActionPerformed

    private void termListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_termListValueChanged
        // TODO add your handling code here:
        String term=(String) termList.getSelectedValue();
        if(term==null){
            return;
        }
        if(term.equals((String)listModel.lastElement())){
            isEdit = true;
        }
        else{
            isEdit = false;
        }
        
        deleteButton.setEnabled(false);
            modifyButton.setEnabled(false);
            sureButton.setEnabled(false);
            cancelButton.setEnabled(false);
            addStuButton.setEnabled(false);
            cancelAddButton.setEnabled(false);
            
        courseBL = factory.createCourseBL(term);
       vos = courseBL.observeInsLeanCour(userInfo.getDepart());
       updateTable();
       v=null;
    }//GEN-LAST:event_termListValueChanged

    private void insTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insTextFieldActionPerformed

    public void TableValueChanged(int i){
        v = vos.get(i);
        if(isEdit){
        deleteButton.setEnabled(true);
        modifyButton.setEnabled(true);
        sureButton.setEnabled(true);
            cancelButton.setEnabled(true);
            addStuButton.setEnabled(true);
            cancelAddButton.setEnabled(true);
        }
        else{
            deleteButton.setEnabled(false);
            modifyButton.setEnabled(false);
            sureButton.setEnabled(false);
            cancelButton.setEnabled(false);
            addStuButton.setEnabled(false);
            cancelAddButton.setEnabled(false);
        }
        //idTextField1.setText(v.getCourseID());
        modualComboBox.setSelectedItem(v.getModule());
        propertyComboBox.setSelectedItem(v.getProperty());
        periodComboBox.setSelectedItem(v.getPeriod());
        isOpenComboBox.setSelectedItem(v.getIsOpen());
        typeComboBox.setSelectedItem(v.getType());
        creditComboBox.setSelectedItem(v.getCredit());
        hourComboBox.setSelectedItem(v.getHour());
        teaIDTextField.setText(v.getTeaID());
        teaNameTextField.setText(v.getTeaName());
        timeTextField.setText(v.getTime());
        //materialTextField.setText(v.getMaterial());
        insTextField.setText(v.getInstitute());
        leanInsTextField.setText(v.getLearnIns());
        
        modualComboBox.setEnabled(false);
        propertyComboBox.setEnabled(false);
        periodComboBox.setEnabled(false);
        isOpenComboBox.setEnabled(false);
        typeComboBox.setEnabled(false);
        creditComboBox.setEnabled(false);
        hourComboBox.setEnabled(false);
        teaIDTextField.setEditable(false);
        teaNameTextField.setEditable(false);
        timeTextField.setEditable(false);
        leanInsTextField.setEditable(false);
        //materialTextField.setText(v.getMaterial());
       // insTextField.setEditable(false);
        //referenceTextArea.setText(v.getReference().replace('=', '\n'));
        //summaryTextArea.setText(v.getSummary().replace('=', '\n'));
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStuButton;
    private javax.swing.JButton cancelAddButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel courseInfoPanel;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton createButton5;
    private javax.swing.JComboBox creditComboBox;
    private javax.swing.JComboBox creditComboBox2;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox hourComboBox;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel insLabel;
    private javax.swing.JTextField insTextField;
    private javax.swing.JComboBox isOpenComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField leanInsTextField;
    private javax.swing.JLabel learnInsLabel;
    private javax.swing.JButton modifyButton;
    private javax.swing.JComboBox modualComboBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox periodComboBox;
    private javax.swing.JComboBox propertyComboBox;
    private javax.swing.JButton sureButton;
    private javax.swing.JTextField teaIDTextField;
    private javax.swing.JTextField teaNameTextField;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JList termList;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField timeTextField;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
    private FullComboBox insFull;
    private MyComboBox learnInsComboBox;
    private GridBagConstraints gridBagConstraints;
    
    /*逻辑处理*/
    private CourseVO cvo;
    private String courseID;//课程号
    private String courseName;//课程名
    private String module;//课程模块：通识通修、学科专业、开放选修、毕业论文/设计
    private String property;//课程性质：必修、指选、选修
    private String type;//课程类别：
    private char order;//序列：A,B,C,D,E,F,G,H,I,J,L
    private String term;//开设学期:1,8
    private int credit;//学分
    private int hour;//周学时
    private String teaName;//授课教师姓名
    private String time;//授课时间
    private String institute;//开设院系
    private String learnIns;//修读院系

    private void updateTable(){
        //vos = courseBL.observeInsLeanCour(userInfo.getDepart());
        String[][] content = new String[vos.size()][3];
        for (int i = 0; i < vos.size(); i++) {

            //初始化table

            content[i][0] = vos.get(i).getCourseID();
            content[i][1] = vos.get(i).getCourseName();
            content[i][2] = vos.get(i).getCredit();
        }
        String[] head = {"课程号","课程名","学分"};
        DefaultTableModel model = new DefaultTableModel(content, head) {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        courseTable.setModel(model);

    }
    
    public void update(){
        listModel.removeAllElements();
        String[] s=courseBL.getAllTerms();
        for(String str:s){
            listModel.addElement(str);
        }
        termList.repaint();
        if(vos!=null){
        vos.clear();
        updateTable();
        }
       
        
         deleteButton.setEnabled(false);
            modifyButton.setEnabled(false);
            sureButton.setEnabled(false);
            cancelButton.setEnabled(false);
            addStuButton.setEnabled(false);
            cancelAddButton.setEnabled(false);
            
             modualComboBox.setSelectedIndex(0);
        propertyComboBox.setSelectedIndex(0);
        periodComboBox.setSelectedIndex(0);
        isOpenComboBox.setSelectedIndex(0);
        typeComboBox.setSelectedIndex(0);
        creditComboBox.setSelectedIndex(0);
        hourComboBox.setSelectedIndex(0);
        teaIDTextField.setText("");
        teaNameTextField.setText("");
        timeTextField.setText("");
        //materialTextField.setText(v.getMaterial());
        leanInsTextField.setText("");
    }
}
