/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Teacher;

import businesslogicservice.userblservice.UserBLService;
import businesslogicservice.userblservice.UserInfoFactory;
import enumeration.ResultMessage;
import javax.swing.JOptionPane;
import vo.uservo.UserInfoVO;

/**
 *
 * @author 天
 */
public class ModifyKeyPanel extends javax.swing.JPanel {
 UserInfoVO v;
 String ip;
 int port;
    /**
     * Creates new form ModifyKeyPanel
     */
    public ModifyKeyPanel(UserInfoVO v,String ip,int port) {
        this.v = v;
        this.ip = ip;
        this.port = port;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPasswordField1 = new javax.swing.JPasswordField();
        newPasswordField2 = new javax.swing.JPasswordField();
        setKeyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        tipLabel = new javax.swing.JLabel();
        oldPasswordField = new javax.swing.JPasswordField();
        newKeyLabel1 = new javax.swing.JLabel();
        newKeyLabel = new javax.swing.JLabel();
        newKeyLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        newPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordField1ActionPerformed(evt);
            }
        });

        newPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordField2ActionPerformed(evt);
            }
        });

        setKeyButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        setKeyButton.setText("确认");
        setKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setKeyButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cancelButton.setText("取消");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        tipLabel.setForeground(new java.awt.Color(255, 0, 51));
        tipLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        oldPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPasswordFieldActionPerformed(evt);
            }
        });

        newKeyLabel1.setBackground(new java.awt.Color(0, 0, 0));
        newKeyLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        newKeyLabel1.setForeground(new java.awt.Color(204, 204, 204));
        newKeyLabel1.setText("原密码");

        newKeyLabel.setBackground(new java.awt.Color(0, 0, 0));
        newKeyLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        newKeyLabel.setForeground(new java.awt.Color(204, 204, 204));
        newKeyLabel.setText("新密码");

        newKeyLabel2.setBackground(new java.awt.Color(0, 0, 0));
        newKeyLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        newKeyLabel2.setForeground(new java.awt.Color(204, 204, 204));
        newKeyLabel2.setText("新密码确认");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newKeyLabel)
                            .addComponent(newKeyLabel1))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(newPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldPasswordField)
                            .addComponent(newPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(newKeyLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(setKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(tipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newKeyLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newKeyLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newKeyLabel2)
                    .addComponent(newPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(tipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setKeyButton)
                    .addComponent(cancelButton))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordField1ActionPerformed
        // TODO add your handling code here:
        setKeyButtonActionPerformed(evt);
    }//GEN-LAST:event_newPasswordField1ActionPerformed

    private void newPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordField2ActionPerformed
        // TODO add your handling code here:
        setKeyButtonActionPerformed(evt);
    }//GEN-LAST:event_newPasswordField2ActionPerformed

    private void setKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setKeyButtonActionPerformed
        // TODO add your handling code here:
        String s1 = new String(oldPasswordField.getPassword());
        if (!v.getPsw().equals(s1)) {
            tipLabel.setText("原密码不对");
            return;
        }
        String s2 = new String(newPasswordField1.getPassword());
        String s3 = new String(newPasswordField2.getPassword());
        if (!s2.equals(s3)) {
            tipLabel.setText("两次密码不一致");
            return;
        }
        v.setPsw(s3);
         UserInfoFactory factory = new UserInfoFactory();
        UserBLService userBL = factory.getUserBLService(ip, port);
        if (userBL.changeUserInfo(v) == ResultMessage.SUCCESS) {
            JOptionPane.showConfirmDialog(this, "修改成功！", null, JOptionPane.OK_OPTION);
            oldPasswordField.setText("");
            newPasswordField1.setText("");
            newPasswordField2.setText("");

        } else {
            JOptionPane.showConfirmDialog(this, "修改失败", null, JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_setKeyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        oldPasswordField.setText("");
        newPasswordField2.setText("");
        newPasswordField1.setText("");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void oldPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPasswordFieldActionPerformed
        // TODO add your handling code here:
        setKeyButtonActionPerformed(evt);
    }//GEN-LAST:event_oldPasswordFieldActionPerformed

    public void update(){
        oldPasswordField.setText("");
            newPasswordField1.setText("");
            newPasswordField2.setText("");
            tipLabel.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel newKeyLabel;
    private javax.swing.JLabel newKeyLabel1;
    private javax.swing.JLabel newKeyLabel2;
    private javax.swing.JPasswordField newPasswordField1;
    private javax.swing.JPasswordField newPasswordField2;
    private javax.swing.JPasswordField oldPasswordField;
    private javax.swing.JButton setKeyButton;
    private javax.swing.JLabel tipLabel;
    // End of variables declaration//GEN-END:variables
}
