/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Student;

import businesslogicservice.selectionblservice.SelectionBLService;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vo.coursevo.CourseVO;
import vo.selectionvo.SelectionVO;

/**
 *
 * @author zili chen
 */
public class PerCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form PerCoursePanel
     */
    
    private String stuID;
    private SelectionBLService selectionbl;
    ArrayList<CourseVO> myCourseList;
    
    public PerCoursePanel(String stuID, SelectionBLService selectionbl) {
        initComponents();
        this.stuID = stuID;
        this.selectionbl = selectionbl;
        
        myCourseList = selectionbl.getMyCourseList(stuID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siftPanel = new javax.swing.JPanel();
        termLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        termList = new javax.swing.JList();
        coursePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        courseListTable = new javax.swing.JTable();
        dropButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(889, 368));

        siftPanel.setBackground(new java.awt.Color(0, 0, 0));
        siftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "筛选课程", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        termLabel.setBackground(new java.awt.Color(0, 0, 0));
        termLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        termLabel.setForeground(new java.awt.Color(204, 204, 204));
        termLabel.setText("学期");

        termList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        termList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "2013年第一学期", "2012年第二学期", "2012年第一学期", "2011年第二学期", "2011年第一学期" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        termList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                termListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(termList);

        javax.swing.GroupLayout siftPanelLayout = new javax.swing.GroupLayout(siftPanel);
        siftPanel.setLayout(siftPanelLayout);
        siftPanelLayout.setHorizontalGroup(
            siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(termLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        siftPanelLayout.setVerticalGroup(
            siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(termLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        coursePanel.setBackground(new java.awt.Color(0, 0, 0));
        coursePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "课程列表", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        courseListTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        courseListTable.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        courseListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "课程号", "课程名称", "学分", "授课老师", "上课时间", "选课类型"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        courseListTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(courseListTable);

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        dropButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dropButton.setText("退选");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(siftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(dropButton)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(siftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(dropButton)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void termListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_termListMouseClicked
        String term_ch = (String)termList.getSelectedValue();
        String term = term_ch.substring(0, 4);
        if(term_ch.charAt(5) == '一'){
            term += "-1";
        }
        else{
            term += "-2";
        }
               
        Iterator<CourseVO> iterator = myCourseList.iterator();
        DefaultTableModel tableModel = (DefaultTableModel)courseListTable.getModel();
        while(iterator.hasNext()){
            CourseVO course = iterator.next();
            
            if(course.getTerm().equals(term)){            
                String courseNum = course.getCourseID();
                String courseName = course.getCourseName();
                String credit = "" + course.getCredit();
                String teacher = course.getTeaName();
                String time = course.getTime();
                String type = course.getProperty();
                    
                tableModel.addRow(new Object[]{courseNum, courseName, credit, teacher, time, type});
            
            }
        }
    }//GEN-LAST:event_termListMouseClicked

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        int selectedRows = courseListTable.getSelectedRows().length;
        DefaultTableModel tablemodel = (DefaultTableModel)courseListTable.getModel();
        if(selectedRows == 1){
            int selectedRow = courseListTable.getSelectedRow();
            String courseNum = (String)tablemodel.getValueAt(selectedRow, 0);
            SelectionVO selectionvo = new SelectionVO(stuID, courseNum);
            if(selectionbl.quitCourse(selectionvo)){
                return;
            }
            else{
                JOptionPane.showMessageDialog(null, "退课失败。。。");
            }
                
            

        }
    }//GEN-LAST:event_dropButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable courseListTable;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JButton dropButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel siftPanel;
    private javax.swing.JLabel termLabel;
    private javax.swing.JList termList;
    // End of variables declaration//GEN-END:variables
}
