/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Student;

import java.util.Calendar;
import vo.uservo.UserInfoVO;

/**
 *
 * @author zili chen
 */
public class PerInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerInfoPanel
     */
    private UserInfoVO student;
    
    public PerInfoPanel(UserInfoVO student) {
        initComponents();
        this.student = student;
        
        Calendar calendar = Calendar.getInstance();
        int nowyear = calendar.get(Calendar.YEAR);
        int nowmonth = calendar.get(Calendar.MONTH);
        int grade = Integer.parseInt(student.getYearIn());
        
        nameLabel1.setText(student.getName());
        birthLabel2.setText(student.getGrade());
        nativeLabel2.setText(student.getIdentification());
        sexLabel2.setText(student.getSex());
        idLabel.setText(student.getID());
        insLabel.setText(student.getDepart());
        gradeLabel2.setText("大一");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        birthLabel = new javax.swing.JLabel();
        insLabel = new javax.swing.JLabel();
        nativeLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        safeLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        setKeyButton = new javax.swing.JButton();
        nameLabel1 = new javax.swing.JLabel();
        idLabel2 = new javax.swing.JLabel();
        insLabel2 = new javax.swing.JLabel();
        birthLabel2 = new javax.swing.JLabel();
        sexLabel2 = new javax.swing.JLabel();
        gradeLabel2 = new javax.swing.JLabel();
        nativeLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(889, 368));

        infoPanel.setBackground(new java.awt.Color(0, 0, 0));
        infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));

        nameLabel.setBackground(new java.awt.Color(0, 0, 0));
        nameLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel.setText("姓名：");

        birthLabel.setBackground(new java.awt.Color(0, 0, 0));
        birthLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        birthLabel.setForeground(new java.awt.Color(204, 204, 204));
        birthLabel.setText("出生日期：");

        insLabel.setBackground(new java.awt.Color(0, 0, 0));
        insLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insLabel.setForeground(new java.awt.Color(204, 204, 204));
        insLabel.setText("学院：");

        nativeLabel.setBackground(new java.awt.Color(0, 0, 0));
        nativeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nativeLabel.setForeground(new java.awt.Color(204, 204, 204));
        nativeLabel.setText("身份证：");

        gradeLabel.setBackground(new java.awt.Color(0, 0, 0));
        gradeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(204, 204, 204));
        gradeLabel.setText("年级：");
        gradeLabel.setToolTipText("");

        sexLabel.setBackground(new java.awt.Color(0, 0, 0));
        sexLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(204, 204, 204));
        sexLabel.setText("性别：");

        idLabel.setBackground(new java.awt.Color(0, 0, 0));
        idLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(204, 204, 204));
        idLabel.setText("学号：");

        safeLabel.setBackground(new java.awt.Color(0, 0, 0));
        safeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        safeLabel.setForeground(new java.awt.Color(204, 204, 204));
        safeLabel.setText("安全信息：您账号的当前安全等级");

        levelLabel.setBackground(new java.awt.Color(0, 0, 0));
        levelLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        levelLabel.setForeground(new java.awt.Color(204, 204, 204));
        levelLabel.setText("高");

        setKeyButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        setKeyButton.setText("修改密码");

        nameLabel1.setBackground(new java.awt.Color(0, 0, 0));
        nameLabel1.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(204, 204, 204));
        nameLabel1.setText("XX");

        idLabel2.setBackground(new java.awt.Color(0, 0, 0));
        idLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        idLabel2.setForeground(new java.awt.Color(204, 204, 204));
        idLabel2.setText("XX");

        insLabel2.setBackground(new java.awt.Color(0, 0, 0));
        insLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        insLabel2.setForeground(new java.awt.Color(204, 204, 204));
        insLabel2.setText("XX");

        birthLabel2.setBackground(new java.awt.Color(0, 0, 0));
        birthLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        birthLabel2.setForeground(new java.awt.Color(204, 204, 204));
        birthLabel2.setText("XX");

        sexLabel2.setBackground(new java.awt.Color(0, 0, 0));
        sexLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        sexLabel2.setForeground(new java.awt.Color(204, 204, 204));
        sexLabel2.setText("XX");

        gradeLabel2.setBackground(new java.awt.Color(0, 0, 0));
        gradeLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        gradeLabel2.setForeground(new java.awt.Color(204, 204, 204));
        gradeLabel2.setText("XX");

        nativeLabel2.setBackground(new java.awt.Color(0, 0, 0));
        nativeLabel2.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        nativeLabel2.setForeground(new java.awt.Color(204, 204, 204));
        nativeLabel2.setText("XX");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addGap(18, 18, 18)
                                .addComponent(idLabel2))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nameLabel1))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(insLabel)
                                .addGap(18, 18, 18)
                                .addComponent(insLabel2))
                            .addGroup(infoPanelLayout.createSequentialGroup()
                                .addComponent(birthLabel)
                                .addGap(18, 18, 18)
                                .addComponent(birthLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nativeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gradeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sexLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexLabel2)
                            .addComponent(gradeLabel2)
                            .addComponent(nativeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(safeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(levelLabel)
                        .addGap(33, 33, 33)
                        .addComponent(setKeyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(124, Short.MAX_VALUE))))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexLabel)
                    .addComponent(nameLabel)
                    .addComponent(nameLabel1)
                    .addComponent(sexLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(gradeLabel)
                    .addComponent(idLabel2)
                    .addComponent(gradeLabel2))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nativeLabel)
                    .addComponent(insLabel2)
                    .addComponent(nativeLabel2)
                    .addComponent(insLabel))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthLabel2)
                    .addComponent(birthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(safeLabel)
                    .addComponent(levelLabel)
                    .addComponent(setKeyButton))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthLabel;
    private javax.swing.JLabel birthLabel2;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JLabel gradeLabel2;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel insLabel;
    private javax.swing.JLabel insLabel2;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nativeLabel;
    private javax.swing.JLabel nativeLabel2;
    private javax.swing.JLabel safeLabel;
    private javax.swing.JButton setKeyButton;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JLabel sexLabel2;
    // End of variables declaration//GEN-END:variables
}
