/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Student;

import businesslogicservice.selectionblservice.SelectionBLService;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vo.coursevo.CourseVO;
import vo.selectionvo.SelectionVO;

/**
 *
 * @author zili chen
 */
public class SelectPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectPanel
     */
    private final int maxCourseNum = 4;
    private String stuID;
    private SelectionBLService selectionbl;
    private ArrayList<CourseVO> totalCourseList;
    private ArrayList<CourseVO> showCourseList;
    private ArrayList<CourseVO> myCourseList;
    
    private String[] day = new String[]{"", "monday", "tuesday", "wednesday", "thursday", "friday"};
    private int[] credit = new int[]{0, 1, 2, 3, 4, 5};
    private String[] type = new String[]{"", "generalCourse", "seminar"};
    private String[] keyword = new String[]{"", "IT", "philosophy"};
    
    
    public SelectPanel(String stuID, SelectionBLService selectionbl) {
        initComponents();
        this.stuID = stuID;
        this.selectionbl = selectionbl;
        
        totalCourseList = selectionbl.getCourseList();
        myCourseList = selectionbl.getMyCourseList(stuID);
        
        Iterator<CourseVO> iterator= myCourseList.iterator();
        DefaultTableModel tableModel = (DefaultTableModel)selectedListTable.getModel();
        while(iterator.hasNext()){
            CourseVO course = iterator.next();
            tableModel.addRow(new Object[]{course.getCourseID(), course.getCourseName()});
        }
        
        iterator = totalCourseList.iterator();
        tableModel = (DefaultTableModel)courseListTable.getModel();
        while(iterator.hasNext()){
            CourseVO course = iterator.next();
            tableModel.addRow(new Object[]{course.getCourseID(), course.getCourseName()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void showTotalCourse(){
        int dayIndex = dayList.getSelectedIndex();
        int creditIndex = creditList.getSelectedIndex();
        int typeIndex = typeList.getSelectedIndex();
        int keywordIndex = keywordList.getSelectedIndex();
    
        showCourseList = (ArrayList<CourseVO>)totalCourseList.clone();
        Iterator<CourseVO> iterator = showCourseList.iterator();
        
        iterator = showCourseList.iterator();
        if(dayIndex > 0){
            while(iterator.hasNext()){
                if(!iterator.next().getTime().equals(day[dayIndex])){
                    iterator.remove();
                }
            }
        }
        
        iterator = showCourseList.iterator();
        if(creditIndex > 0){
            while(iterator.hasNext()){
                int c1=Integer.parseInt(iterator.next().getCredit());
                if(c1!= credit[creditIndex]){
                    iterator.remove();
                }
            }
        }
        
        /*iterator = showCourseList.iterator();
        if(typeIndex > 0){
            while(iterator.hasNext()){
                ///////////undefined course type
            }
        }*/
        
        /*iterator = showCourseList.iterator();
        if(keywordIndex > 0){
            while(iterator.hasNext()){
                ///////////undefined coures keyword
            }
        }*/
        
        courseListTable.removeAll();
        iterator = showCourseList.iterator();
        DefaultTableModel tableModel = (DefaultTableModel)courseListTable.getModel();
        while(iterator.hasNext()){
            CourseVO course = iterator.next();
            tableModel.addRow(new Object[]{course.getCourseID(), course.getCourseName()});
        }
        
        
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siftPanel = new javax.swing.JPanel();
        keywordLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dayList = new javax.swing.JList();
        dayLabel = new javax.swing.JLabel();
        creditLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        creditList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        typeList = new javax.swing.JList();
        typeLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        keywordList = new javax.swing.JList();
        coursePanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        courseListTable = new javax.swing.JTable();
        viewInfoButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        selectedPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        selectedListTable = new javax.swing.JTable();
        dropButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(889, 368));

        siftPanel.setBackground(new java.awt.Color(0, 0, 0));
        siftPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "筛选课程", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        keywordLabel.setBackground(new java.awt.Color(0, 0, 0));
        keywordLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        keywordLabel.setForeground(new java.awt.Color(204, 204, 204));
        keywordLabel.setText("关键字");

        dayList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dayList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        dayList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dayListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dayList);

        dayLabel.setBackground(new java.awt.Color(0, 0, 0));
        dayLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dayLabel.setForeground(new java.awt.Color(204, 204, 204));
        dayLabel.setText("星期");

        creditLabel.setBackground(new java.awt.Color(0, 0, 0));
        creditLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        creditLabel.setForeground(new java.awt.Color(204, 204, 204));
        creditLabel.setText("学分");

        creditList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        creditList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1", "2", "3", "4", "5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        creditList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(creditList);

        typeList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "通识课", "研讨课", "网络课程", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        typeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                typeListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(typeList);

        typeLabel.setBackground(new java.awt.Color(0, 0, 0));
        typeLabel.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(204, 204, 204));
        typeLabel.setText("类别");

        keywordList.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        keywordList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "信息", "哲学", "艺术", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        keywordList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keywordListMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(keywordList);

        javax.swing.GroupLayout siftPanelLayout = new javax.swing.GroupLayout(siftPanel);
        siftPanel.setLayout(siftPanelLayout);
        siftPanelLayout.setHorizontalGroup(
            siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addComponent(keywordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditLabel)
                            .addComponent(dayLabel)
                            .addComponent(typeLabel))
                        .addGap(24, 24, 24)
                        .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        siftPanelLayout.setVerticalGroup(
            siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siftPanelLayout.createSequentialGroup()
                .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(dayLabel))
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(creditLabel))
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(typeLabel)))
                .addGap(23, 23, 23)
                .addGroup(siftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siftPanelLayout.createSequentialGroup()
                        .addComponent(keywordLabel)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        coursePanel.setBackground(new java.awt.Color(0, 0, 0));
        coursePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "课程列表", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        courseListTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        courseListTable.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        courseListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "课程号", "课程名"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        courseListTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane6.setViewportView(courseListTable);

        viewInfoButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        viewInfoButton.setText("查看信息");
        viewInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInfoButtonActionPerformed(evt);
            }
        });

        selectButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        selectButton.setText("选择课程");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
        coursePanel.setLayout(coursePanelLayout);
        coursePanelLayout.setHorizontalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(viewInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectButton)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        coursePanelLayout.setVerticalGroup(
            coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectButton)
                    .addComponent(viewInfoButton))
                .addGap(13, 13, 13))
        );

        selectedPanel.setBackground(new java.awt.Color(0, 0, 0));
        selectedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true), "已选课程", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("微软雅黑", 0, 14), new java.awt.Color(204, 204, 204))); // NOI18N

        selectedListTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        selectedListTable.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        selectedListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "课程号", "课程名"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        selectedListTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane7.setViewportView(selectedListTable);

        dropButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        dropButton.setText("退选");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        submitButton.setText("提交");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectedPanelLayout = new javax.swing.GroupLayout(selectedPanel);
        selectedPanel.setLayout(selectedPanelLayout);
        selectedPanelLayout.setHorizontalGroup(
            selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectedPanelLayout.createSequentialGroup()
                        .addGap(0, 55, Short.MAX_VALUE)
                        .addComponent(dropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        selectedPanelLayout.setVerticalGroup(
            selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(dropButton))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(siftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coursePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dayListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayListMouseClicked
        showTotalCourse();
    }//GEN-LAST:event_dayListMouseClicked

    private void creditListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditListMouseClicked
        showTotalCourse();
    }//GEN-LAST:event_creditListMouseClicked

    private void typeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_typeListMouseClicked
        showTotalCourse();
    }//GEN-LAST:event_typeListMouseClicked

    private void keywordListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keywordListMouseClicked
        showTotalCourse();
    }//GEN-LAST:event_keywordListMouseClicked

    private void viewInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInfoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewInfoButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        DefaultTableModel mytablemodel = (DefaultTableModel)selectedListTable.getModel();
        if(mytablemodel.getRowCount() >= maxCourseNum){
            JOptionPane.showMessageDialog(null, "选课数已达上限！");
            return;
        }
        
        int selectRows = courseListTable.getSelectedRows().length;
        DefaultTableModel tablemodel = (DefaultTableModel)courseListTable.getModel();
        
        if(selectRows == 1){
            int selectedRow = courseListTable.getSelectedRow();
            String courseNum = (String)tablemodel.getValueAt(selectedRow, 0);
            String courseName = (String)tablemodel.getValueAt(selectedRow, 1);
            SelectionVO selectionvo = new SelectionVO(courseNum, stuID);
            if(selectionbl.addCourse(selectionvo)){
                
                mytablemodel.addRow(new Object[]{courseNum, courseName});
                
            }
            else{
                JOptionPane.showMessageDialog(null, "选择失败。。。");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "请选择一门课程！");
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        int selectedRows = selectedListTable.getSelectedRows().length;
        DefaultTableModel tablemodel = (DefaultTableModel)selectedListTable.getModel();
        
        if(selectedRows == 1){
            int selectedRow = selectedListTable.getSelectedRow();
            String courseNum = (String)tablemodel.getValueAt(selectedRow, 0);
            SelectionVO selectionvo = new SelectionVO(courseNum, stuID);
            if(selectionbl.deleteCourse(selectionvo)){
                tablemodel.removeRow(selectedRow);
            }
            else{
                JOptionPane.showMessageDialog(null, "退选失败。。。");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "请选择一门课程！");
        }
    }//GEN-LAST:event_dropButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(!selectionbl.verify()){
            JOptionPane.showMessageDialog(null, "提交失败！");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable courseListTable;
    private javax.swing.JPanel coursePanel;
    private javax.swing.JLabel creditLabel;
    private javax.swing.JList creditList;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JList dayList;
    private javax.swing.JButton dropButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JList keywordList;
    private javax.swing.JButton selectButton;
    private javax.swing.JTable selectedListTable;
    private javax.swing.JPanel selectedPanel;
    private javax.swing.JPanel siftPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JList typeList;
    private javax.swing.JButton viewInfoButton;
    // End of variables declaration//GEN-END:variables
}
